### ISSUE TITLE
asciinema demos tip

### ISSUE THREAD

**Issue by sickill** [elixir-lang/elixir-lang.github.com#1000]
I just added ability to specify number of columns/lines to asciinema player when you're embedding from asciinema.org via `<script>` tag (updated [embedding docs](https://asciinema.org/docs/embedding)).

For example, you can adjust the height of all demos in the recent 1.5 post by doing this:

```html
<script type="text/javascript" src="https://asciinema.org/a/iAOk0yaZtQDsuJqn2sXa1FRQW.js" id="asciicast-iAOk0yaZtQDsuJqn2sXa1FRQW" async data-rows="15"></script>
```

(notice added `data-rows="15"` attribute, there's also `data-cols="xxx"` for width)

By doing this you can make demos more compact in the blog post. You can test specific values by appending `?rows=15` to recording URL: https://asciinema.org/a/iAOk0yaZtQDsuJqn2sXa1FRQW?rows=15

That's just a tip, feel free to ignore it :)

**Comment by josevalim** [comment]
Oh, you are the creator of asciinema! This was the first time I used it and I absolutely loved it. It just worked™. I will do the data-rows thing, thank you!

**Comment by sickill** [comment]
Btw, I'm porting the web app gradually to Elixir ;) Live terminal streaming is coming soon, thanks to Phoenix channels 😎
