### ISSUE TITLE
Inconsistency within `Task and gen_tcp` section

### ISSUE THREAD

**Issue by coryc5** [elixir-lang/elixir-lang.github.com#1002]
Hello,

I'm raising this as an issue since I don't know how you'd prefer to resolve this, but the recent 1.5 update resulted in an inconsistency within the "Task and gen_tcp" chapter of the the Mix and OTP guide, in particular these two sections:

```elixir
  def start(_type, _args) do
    children = [
      {Task, fn -> KVServer.accept(4040) end}
    ]

    opts = [strategy: :one_for_one, name: KVServer.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

> Yes, it works! If you kill the client, the whole server will still crash. **But you will see that another one starts right away.** However, does it scale?

However, unlike `Supervisor.Spec.worker/3`, because `Task.child_spec/1` defaults to a restart option of `:temporary` and not `:permanent` this restart does not happen.

Like I said, not sure how you'd prefer to change this but the official Task docs suggest defining Tasks within a module and that together with `use Task, restart: :permanent` could be one option.

**Comment by josevalim** [comment]
Good catch!

We do talk about this by the end of the chapter. So maybe we just remove
this reference for now?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by coryc5** [comment]
Ah, I see. I had not made it to the end. I think in that case you're right it does make sense to just remove the reference to fault tolerance at that point in the guide. I will submit a PR.
