### ISSUE TITLE
Learning question: warning: variable “context” does not exist and is being expanded to “context()” in ets guide 

### ISSUE THREAD

**Issue by TangMonk** [elixir-lang/elixir-lang.github.com#1014]
In Elixir official guide: https://elixir-lang.org/getting-started/mix-otp/ets.html

There is a `setup` callback in test case: 

      setup context do
        {:ok, _} = start_supervised({KV.Registry, name: context.test})
        %{registry: context.test}
      end

Then I following the guide, and after write the test case. I execute the `mix test test/registry_test.exs`, warnings and errors throw to me: 

    warning: variable "context" does not exist and is being expanded to "context()", please use parentheses to remove the ambiguity or change the variable name
      test/registry_test.exs:5
    
    warning: variable "context" does not exist and is being expanded to "context()", please use parentheses to remove the ambiguity or change the variable name
      test/registry_test.exs:6
    
    ** (CompileError) test/registry_test.exs:5: undefined function context/0
        (stdlib) lists.erl:1338: :lists.foreach/2
        (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
        (elixir) lib/code.ex:376: Code.require_file/2
        (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5

It seems treat `context` as a function, but `context.test` should be an atom. How to fix that?

thanks

**Comment by skbolton** [comment]
Its easy to miss the change they do in the example. If you look closely they have you type this in the setup block
```
 setup context do
    _ = start_supervised!({KV.Registry, name: context.test})
    %{registry: context.test}
  end
```
Notice them passing the context value into the setup block
