### ISSUE TITLE
getting started guide, basic-types: immutability of lists?

### ISSUE THREAD

**Issue by no-stack-dub-sack** [elixir-lang/elixir-lang.github.com#1020]
Hi, 
I am brand new to Elixir, and as such, I think it gives me an interesting perspective when reading this material, so thought I'd take this to heart and open an issue (by the way, so far I think the guide is great! concise, well-written, and super clear):

> If you find any errors in the tutorial or on the website, please report a bug or send a pull request to our issue tracker.

One thing that I thought could have been slightly more clear is regarding the immutability of (Linked) Lists. For Tuples, it is very clear that when you call `put_elem/3`, a new tuple is returned, and the original variable `list` is unaffected. 

In the lines following this example, the nature of immutability in Elixir is described, however, this left me with a couple of questions about Lists. The examples around concatenation and subtraction are not quite analogous to the tuple example in the sense that there is no clear indication as to whether or not this is an immutable operation. 

For example, this shows us that concatenation and subtraction is happening (and suggests that a new list is returned), but since there is no assignment here, it's harder to tell:
```
iex> [1, 2, 3] ++ [4, 5, 6]
[1, 2, 3, 4, 5, 6]
iex> [1, true, 2, false, 3, true] -- [true, false]
[1, 2, 3, true]
```
A more clear example might be something like:
```shell
iex> list = [1, 2, 3]
iex> list ++ [4, 5, 6] # does this concatenation create a new list or is the original list modified in place?
[1, 2, 3, 4, 5, 6]
iex> list # [1, 2, 3] or [1, 2, 3, 4, 5, 6]
# ???
```
Based on this note on immutability, I would think the same would hold true for prepending or appending to lists (i.e., original data structure is not changed, rather a new list is created in memory):
> ...Elixir data types are immutable. By being immutable, Elixir code is easier to reason about as you never need to worry that any code might be mutating your data structure in place.

But the following on tuples vs. lists does not seem to support that, and suggests that only tuples are created newly in memory when "changed":
> Tuples, on the other hand, are stored contiguously in memory. ... However, updating or adding elements to tuples is expensive because it requires copying the whole tuple in memory.

Anyway, just my perspective as a total newcomer, not a huge deal either way. If maintainers disagree, I'm happy to close the issue, on the other hand, if you think there is room for improvement here, I'd happily make a PR. 

Overall, I'm excited to learn more and get further through the guide. Thanks!

**Comment by josevalim** [comment]
Welcome @no-stack-dub-sack !

I agree there is room for improvement here. The principle here is that lists and tuples they are immutable but some operations allow sharing of a base structure. This sharing is only possible by immutability itself since that, if two data structures share something, there is no chance changing one would change the other, since we can't change things on the same place.

So maybe it is better to clarify that the issue with tuples is not necessarily that they are copied but rather that they can't share a common ground?

What do you think?

**Comment by no-stack-dub-sack** [comment]
Hey @josevalim, thanks for the quick feedback! 

Yes, I think that makes sense, and would definitely make things more clear if explained here. 

So basically, in the following example, the important distinction is found in the second set of comments. 
Is this understanding all correct?
```shell
list = [1, 2, 3]
new_list = list ++ [4, 5, 6]

# ++ allows sharing of base structure list
# new_list "points" to list in memory for these elements
# and in effect new_list "shares" [1, 2, 3] with list
# ok since list is immutable

IO.inspect(list) # [1, 2, 3]
IO.inspect(new_list) # [1, 2, 3, 4, 5, 6]

tuple = {:ok, "hello"}
new_tuple = put_elem(tuple, 1, "world")

# put_elem/3 gives the illusion of sharing, 
# but in reality tuple and new_tuple share no base structure
# new_tuple is a new memory allocation, derived, but completely distinct from tuple 

IO.inspect(tuple) # {:ok, "hello"}
IO.inspect(new_tuple) # {:ok, "world"}
```

**Comment by josevalim** [comment]
Almost there!

It is important to highlight that lists share the *tail*. So `list ++ [4, 5, 6]` won't share anything but `[1, 2, 3] ++ list`.

It is also worth noting that no structure does a deep copy. So the `new_tuple` is a whole new container but both `tuple` and `new_tuple` point to the same elements in memory (except by the elements replaced/updated).

So both lists and tuples are "collection of pointers" with different structures.

**Comment by no-stack-dub-sack** [comment]
@josevalim Ahh... ok, thanks for the clarification! I'm seeing it a bit better now. 

So going back to the original issue, perhaps it is just a lack of initial understanding of how these structures work that led to my misunderstanding of the getting started guide - which almost becomes a "chicken or the egg" kind of situation - the guide provides a valuable baseline, but one that's hard to fully grasp until more learning is done. At any rate, the getting started guide has done it's job in provoking a deeper understanding. 

I think your suggestion sounds good, but I would defer to your discretion entirely (for obvious reasons :smile:) on whether or not you think anything should actually be changed. 

Thanks again!

**Comment by josevalim** [comment]
Updated here: c3be903d12d8aaf9de49d7d50ea4ba9ec744a583

Let me know what you think!

**Comment by no-stack-dub-sack** [comment]
@josevalim Yes! 🎉 

 I think this makes a huge difference in making the guide easy to understand on a first pass! Introducing the idea of immutability in the lists section seems more natural and sets up the understanding for the discussion of tuples shortly after. The concept of list and tuples sharing contents is also super helpful, and drives home the point of why immutability is good :smile: 

Wrote my first lines of Elixir a couple days ago and looking forward to learning more!
