### ISSUE TITLE
Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly. 

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-lang/elixir-lang.github.com#1035]
From ruby when caling the jekyll command:
```
Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly. 
```

It speaks about this file:  elixir-lang.github.com/_config.yml

**Comment by richpar3** [comment]
No answer on this? This happens to me too whenever I run "jekyll serve." My css is also not rendering

**Comment by arjunkrishnababu96** [comment]
I had a similar issue for a different project (which used jekyll).

Here's the fix that worked for me:

1. Open `_config.yml` in a text editor
2. Find the line that says "gems:"
3. Replace the word "gems" with "plugins"

**Comment by carlosdelfino** [comment]
I make changes and now I get this error:

'''
$ bundle exec jekyll serve --incremental
jekyll 3.7.3 | Error:  (C:/Users/Admin/workspace/ComercialSimples/docs/_config.yml): did not find expected key while parsing a block mapping at line
1 column 1
'''

my _config.yml:

'''
theme: jekyll-theme-leap-day
title: Comercial Simples Nordeste 
description: "Soluções e Integrações Inteligentes - Windows/Linux a melhor solução para Automação de sua Empresa"
keywords: Automação, Comercial, Sistema, CRM, Integração, Solução, ERP, Inteligente, Internet, Loja Virtual, Loja, Virtual, Hotmart
show_downloads: true
google_analytics: UA-21710445-1
locale: pt_BR
lang: pt_BR
charset: utf-8
encoding: utf-8
repository: carlosdelfino/ComercialSimples

plugins: 
   - jekyll-github-metadata
   - jekyll-seo-tag]

 exclude:
  - "/script/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "vendor"
  - "lib"
  - "config.rb"
  - ".sass-cache"
  - "Capfile"
  - "config"
  - "log"
  - "Rakefile"
  - "Rakefile.rb"
  - "tmp"
  - "_tmp"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE"
  - "_backup*"
  - "*.bck"
  - "*.tmp"
  - "/*.bck/"
  - "/*.tmp/"
  - ".git"
  - ".git*"
'''

**Comment by OvermindDL1** [comment]
@carlosdelfino Are you in the correct repo?  This is about the Elixir Programming Language Website.

**Comment by 766** [comment]
Solved my problem thx
