### ISSUE TITLE
Permission to use Elixir logo

### ISSUE THREAD

**Issue by JustinBeckwith** [elixir-lang/elixir-lang.github.com#1036]
Greetings folks!  We're doing some Elixir related work, and we'd like to use the Elixir logo if possible on one of our web pages.  Is there a process for getting permission?

**Comment by josevalim** [comment]
Hi Justin, unfortunately we are not allowed to give permission while the trademark process is running according to our lawyers feedback. To make a long story short, until we have the trademark, the logo is not really ours, so we can't give permission to something that we do not own. We would be putting you and us at risk. Apologies.
