### ISSUE TITLE
Code examples assume that "use Application" defines a Supervisor inside that module

### ISSUE THREAD

**Issue by sternmull** [elixir-lang/elixir-lang.github.com#1040]
In the guide in "Supervisor and Application":
```
defmodule KV do
  use Application

  def start(_type, _args) do
    KV.Supervisor.start_link(name: KV.Supervisor)
  end
end
```
In the hexdocs for Application:
```
defmodule MyApp do
  use Application

  def start(_type, _args) do
    MyApp.Supervisor.start_link()
  end
end
```
In both cases Supervisor is undefined.

**Comment by josevalim** [comment]
In the guide, the KV.Supervisor is built somewhere in the same chapter or in the previous chapter. I.e. it is dependent on previous code. The Application docs one I have fixed in master, thanks!
