### ISSUE TITLE
https://elixir-lang.org is not available via IPv4

### ISSUE THREAD

**Issue by kroburg** [elixir-lang/elixir-lang.github.com#1047]
Hi!

https://elixir-lang.org is not available via IPv4 from Moscow Russia. IPv6 works. Also I can reach site using Tor network.

I can see that elixir-lang.org resolved to 104.28.11.110 and 104.28.10.110.

My ISP support says that site blocked IPv4 for several other countries.

**Comment by josevalim** [comment]
We are aware but we are not sure of what we can do. We use cloudflare for the SSL and I believe those have been reported there. Here is a mirror from elixir forum: http://elixir-lang-mirror.elixirforum.com/

**Comment by kroburg** [comment]
I don't understand.
Some Cloudflare IPs are blocked by court order or what?

Then there is some ambiguity. Usually I can reach any blocked site from work (because it is internet search portal). This time I can't do that via ipv4. We have ipv6 at work, so it works.

**Comment by ericmj** [comment]
I don't know it's by court order but Russia blocks much of Cloudflare's network. Many CDNs have these kinds of problems in different parts of the world.

You have to contact Cloudflare about why you can't reach from work, that's not something we can answer unfortunately.

**Comment by kroburg** [comment]
I got it. Looks like Cloudflare cannot do anything about it, except limit Internet freedom. So we need to appeal that (ip block) decision in Russia.

As a temporary measure, Cloudflare can change to the not blocked ip. But this is fragile solution.
