### ISSUE TITLE
Should we consider adding some documentation on how to upgrade one's Elixir version?

### ISSUE THREAD

**Issue by boddhisattva** [elixir-lang/elixir-lang.github.com#1049]
Dear Team,

Greetings :). 

**Context:** I was just getting back to doing some stuff on Elixir after a break for a few months and I realized that my Elixir version on my macbook is old. I couldn't find any documentation on how to upgrade my Elixir version and I'm using homebrew. After some googling around I found that homebrew users could update their Elixir versions using the below two steps:

1. `brew update`
2.  `brew upgrade elixir`

**Proposal:**

I was wondering if it would be a good idea to add this to the documentation somewhere. If so, I'd like to submit a PR to update this for homebrew users and may be other people could help out with updating with the appropriate steps for upgrading Elixir on other platforms. Please let me know your thoughts on this and where do you think this documentation could ideally reside if we'd like to add this to https://elixir-lang.org. I was thinking we may need a new page similar to the current [Install page](https://elixir-lang.org/install.html) on the website but it's good to get your thoughts on this before we could decide on the way forward.

Thank you.

**Comment by josevalim** [comment]
Thanks @boddhisattva! I am unsure if we should because it is about how to use the tool you used to instal it and not about Elixir per-se. The most important part, which is listing of the tools, we already do.

I could see adding an update instruction for the manual steps, since those are Elixir specific, but not to every package manager.

**Comment by boddhisattva** [comment]
Thanks for your response @josevalim, I do see where you're coming from. If one knows how to use `brew` in general, they could figure this out. My intention was only to make it easier for the end user. 

> I could see adding an update instruction for the manual steps, since those are Elixir specific, but not to every package manager

With the above statement in mind, can you please elaborate on what exactly you'd like to propose? Sorry, if I didn't completely get your point but If you think adding the steps for homebrew package manager could be useful with the above statement in mind, I could send a PR. You could probably also mention for which package managers we don't necessarily need to add the update instructions so that may be others looking at this issue could keep this in mind and contribute accordingly.

**Comment by josevalim** [comment]
I meant adding those steps to this section in particular: https://elixir-lang.org/install.html#compiling-from-source-unix-and-mingw

All others are very specific to the current package manager and it is probably best for the developers to consult the package manager. :)

**Comment by boddhisattva** [comment]
Sure @josevalim 👍 , Thank you for clarifying :)

**Comment by josevalim** [comment]
Glad to! I will close this for now but if someone beleives update instructions would be welcome to the linked section above, please send a PR!
