### ISSUE TITLE
typo in https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html

### ISSUE THREAD

**Issue by valsamakis** [elixir-lang/elixir-lang.github.com#1050]
The Unicode standard assigns code points to many of the characters we know. For example, the letter a has code point 97 while the letter ł has code point 322. **When writing the string "hełło" to disk, we need to convert this code point to bytes.**

The last sentence does not make sense to me. It would be better say : **When writing the string "hełło" to disk, we need to convert this sequence of characters to bytes.**

**Comment by josevalim** [comment]
Beautiful, please send a pull request? :)
