### ISSUE TITLE
Elixir docs bang for DuckDuckGo does not work

### ISSUE THREAD

**Issue by supernintendo** [elixir-lang/elixir-lang.github.com#1061]
Hello. I wasn't sure whether to submit this here, some HexDocs repo, DuckDuckGo support or somewhere else. Apologies if it doesn't belong. Anyway, the `!elixir-docs` bang for the DuckDuckGo search engine (listed on https://duckduckgo.com/bang) does not work as expected. For example, when searching for `!elixir-docs Kernel` I would expect to be redirected to the Elixir documentation page for the `Kernel` module ([link](https://hexdocs.pm/elixir/Kernel.html)) or a HexDocs search for that term. Instead, I am presented with one DuckDuckGo search result titled "Redirecting" which links to the docs page on elixir-lang.org ([link](https://elixir-lang.org/docs.html)). This occurs for other search terms as well.

Just a low priority issue I came across and thought I'd report here. Thanks to all Elixir and Erlang contributors and have a great day.

**Comment by ericmj** [comment]
I think this issue needs to be reported to duckduckgo, we don't know or control how that search works.

**Comment by josevalim** [comment]
Yes, please follow up with duckduckgo and let us know. If there is anything we can do, please ping here or open up a new issue. :heart:
