### ISSUE TITLE
Proposal - Can we consider adding a Debugging Section to the Getting Started guides?

### ISSUE THREAD

**Issue by boddhisattva** [elixir-lang/elixir-lang.github.com#1065]
As a beginner to Elixir, I started learning the concepts of the language by reading up the Getting Started Guides and also by solving some [exercises in the Elixir track of Exercism](http://exercism.io/languages/elixir/exercises). As I was solving more problems on Exercism, they were times when I wasn't sure how to use `IEx.pry` wrt an Elixir script until I came across [this discussion](https://groups.google.com/forum/#!msg/elixir-lang-talk/8VejRgYw2hQ/eZPNcdMlEQAJ) and then realised, I could now go ahead and add `IEx.pry` to my code and call any part of the same script through Elixir's interactive shell. 

I believe in general many beginners to Elixir could benefit from a `Debugging in Elixir` guide and I'd be happy to work on writing one if we're for the idea of having it as part of the Getting Started with Elixir section. I've also seen a [discussion here](https://groups.google.com/forum/#!topic/elixir-lang-talk/9e7JjfX70NA) on elixir-lang talk mailing list where they talk about a missing Debugging section as part of the Getting Started series.

If there's an interest on having one, I was thinking of covering a few examples related to the usage of:
1. IO.puts
2. IO.inspect
3. IEx.pry

Please feel free to share your thoughts on the above and also please feel free to suggest what you'd like to see covered additionally in a basic guide of Debugging with Elixir for beginners so that I can work accordingly on the documentation for this if we're planning to have one.

Thank you :)

**Comment by josevalim** [comment]
I believe that's a great idea. I don't think we need to include IO.puts, if we have IO.inspect. I would also mention :observer and :debugger coming from Erlang, as well as the new IEx.break!. It can be a new chapter after the typespec and behaviour one.

**Comment by boddhisattva** [comment]
Thank you @josevalim 👍 . I aim to push a WIP PR trying this out for `IO.inspect` and `IEx.pry` for starters just to get some initial feedback based on how I'm planning to structure the documentation wrt this section and proceed with working on mentioning about `:observer` , `:debugger` and `IEx.break!` on an incremental basis based on the received feedback wrt `IO.inspect` and `IEx.pry` related examples. Hope that works, Thank you.

**Comment by josevalim** [comment]
Sounds perfect! Let’s get started with those two and then increment as
necessary.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by boddhisattva** [comment]
@josevalim, other collaborators on this project and members in the community: I've pushed a WIP PR [here](https://github.com/elixir-lang/elixir-lang.github.com/pull/1067). This covers debugging using `IO.inspect/2` for starters. I look forward to your feedback before I start work on the other ways through which one can debug their Elixir code(based on the above discussion). Thank you.

**Comment by josevalim** [comment]
Closing in favor of the PR.
