### ISSUE TITLE
Regarding mix and OTP guide: defmodule KV.Mixfile or KV.MixProject

### ISSUE THREAD

**Issue by ghraka** [elixir-lang/elixir-lang.github.com#1077]
Hi Everyone, 

I am a new learner in Elixir. I was going through the mix and OTP guide. I generated the new mix project using `$ mix new kv --module KV`. The mix.exs file generated has KV.MixProject module whereas the guides has KV.Mixfile. Is this a new addition to elixir 1.6? I couldn't find anything related to this change in the 1.6 release notes. Can anyone give some information about this?

**Comment by josevalim** [comment]
We have updated it maybe on v1.4 or v1.5. FWIW, it doesn't make any difference, although we should definitely update the guides to avoid confusion. Can you please send a PR? :)
