### ISSUE TITLE
ETS page mentions BucketSupervisor.start_bucket method, but DynamicSupervisor page tutorial seems to have removed that part.

### ISSUE THREAD

**Issue by cschar** [elixir-lang/elixir-lang.github.com#1088]
Hi, i was going through the tutorial on learning Mix & OTP and I think I came across an inconsistency?

In the ETS page:
https://elixir-lang.org/getting-started/mix-otp/ets.html#ets-as-a-cache

The code uses the DynamicSupervisor.start_bucket method
```def handle_cast({:create, name}, {names, refs}) do
    # 5. Read and write to the ETS table instead of the map
    case lookup(names, name) do
      {:ok, _pid} ->
        {:noreply, {names, refs}}
      :error ->
        {:ok, pid} = KV.BucketSupervisor.start_bucket()       <-----------
        ref = Process.monitor(pid)
        refs = Map.put(refs, ref, name)
        :ets.insert(names, {name, pid})
        {:noreply, {names, refs}}
    end
  end
```

The old dynamic supervisor page uses the start_bucket/0 method:

http://webcache.googleusercontent.com/search?q=cache:O4_s6GHrSMsJ:elixir-lang.github.io/getting-started/mix-otp/dynamic-supervisor.html+&cd=4&hl=en&ct=clnk&gl=ca

But it seems the new page makes no mention of it, and implements the functionality differently?

http://elixir-lang.github.io/getting-started/mix-otp/dynamic-supervisor.html

I suspect the ETS tutorial page needs to be updated to reflect this or?

**Comment by josevalim** [comment]
Yes, it has just been fixed in master. thank you!
