### ISSUE TITLE
Broken example in Getting Started -> Comprehensions

### ISSUE THREAD

**Issue by jammon** [elixir-lang/elixir-lang.github.com#1122]
In Getting Started -> Comprehensions the first "unoptimized" example about Pythagorean Triples contains the guard `a + b + c <= n,` which seems somewhat unintuitive and excludes some results (e.g. `{7, 24, 25},`). 
In the optimized version this line reads `a + b >= c,` which is a sensible guard.

**Comment by josevalim** [comment]
Please see previous discussions and issues on the topic. Given the amount
of back and forth, I would rather move this example to something else.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
The example has been removed, we will look for something else less prone to confusion. Thank you!
