### ISSUE TITLE
Epub guide needs a class for formatting code around backticks

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#1142]
`<code class="inline">` has no formatting style.
you cannot tell the difference between what's code and regular text

@milmazz

**Comment by milmazz** [comment]
@eksperimental could please tell me on which guide and page are you seeing that behavior? That way would be more easy for me to see what's wrong.

**Comment by eksperimental** [comment]
it's consistent across the three epub guides.
looks like the style is missing
