### ISSUE TITLE
Wrong link in "Observer" section of "Debugging" chapter

### ISSUE THREAD

**Issue by FumioNonaka** [elixir-lang/elixir-lang.github.com#1144]
["Observer" section of "Debugging" chapter](https://elixir-lang.org/getting-started/debugging.html#observer)

> We explore the Observer in the context of an actual project [in the Dynamic Supervisor chapter of the Mix & OTP guide](https://elixir-lang.org/getting-started/mix-otp/dynamic-supervisor.html).

Wrong link: "[Supervisor and Application](https://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html)"
Correct link: "[Dynamic supervisors](https://elixir-lang.org/getting-started/mix-otp/dynamic-supervisor.html)"

**Comment by josevalim** [comment]
@FumioNonaka good catch, can you please send a PR? :+1:
