### ISSUE TITLE
Please clarify "common extension point" in the getting started guide

### ISSUE THREAD

**Issue by brianpeiris** [elixir-lang/elixir-lang.github.com#1160]
The ["alias, require, and import" chapter](https://elixir-lang.org/getting-started/alias-require-and-import.html) of the guide mentions that `use` is a "common extension point". This was probably the most perplexing part of the guide to me. 
The concept of an "extension point" is never explained. Is the idea of an "extension point" unique to Elixir? Is it a core concept? If `use` is a "common" extension point, what are other examples of extension points?
Googling the phrase does not provide much help either. I'd suggest you elaborate on it, either inline or link to a separate glossary, or change the wording entirely.

**Comment by josevalim** [comment]
Excellent feedback, thank you!

**Comment by josevalim** [comment]
I have pushed the commit above, let me know if you think we can still do better. Feel free to send a PR too. :)

**Comment by brianpeiris** [comment]
Great! That clears things up a lot. Thanks for the quick response!
