### ISSUE TITLE
MIX AND OTP "ETS" tells the example code should have failures but it works fine

### ISSUE THREAD

**Issue by FumioNonaka** [elixir-lang/elixir-lang.github.com#1161]
### 2. Race conditions?
> "This time we should be down to one or two intermittent failures:"
https://github.com/elixir-lang/elixir-lang.github.com/edit/master/getting-started/mix-otp/ets.markdown#L212

But my code written based on the guide indicates "0 failures" while I tried to write it three times.

```
$ mix test --trace

KV.BucketTest
  * test are temporary workers (0.03ms)
  * test stores values by key (0.03ms)

KV.RegistryTest
  * test removes bucket on crash (1.7ms)
  * test removes buckets on exit (0.1ms)
  * test spawns buckets (0.08ms)

KVTest


Finished in 0.05 seconds
5 tests, 0 failures

Randomized with seed 614719
```

I tried to change `KV.RegistryTest` as follows:

```
test "removes buckets on exit", %{registry: registry} do
  KV.Registry.create(registry, "shopping")
  {:ok, bucket} = KV.Registry.lookup(registry, "shopping")
  Agent.stop(bucket)
  assert KV.Registry.lookup(registry, "shopping") == :oops  # :error
end
```

`KV.Registry.lookup` properly returns `:error`.

```
$ mix test test/kv/registry_test.exs
..

  1) test removes buckets on exit (KV.RegistryTest)
     test/kv/registry_test.exs:19
     Assertion with == failed
     code:  assert KV.Registry.lookup(registry, "shopping") == :oops
     left:  :error
     right: :oops
     stacktrace:
       test/kv/registry_test.exs:23: (test)



Finished in 0.04 seconds
3 tests, 1 failure

Randomized with seed 16914
```

**Comment by josevalim** [comment]
Since it is race condition, you may not see them at all. :)

I have updated the text to clarify you may not actually see it: https://github.com/elixir-lang/elixir-lang.github.com/commit/b797c5ed37e823f31ac3126d9316263cc5db18cc

Thanks @FumioNonaka!

**Comment by FumioNonaka** [comment]
Thank you very much for your clarification, José.
