### ISSUE TITLE
www.elixir-lang.org certificate expired

### ISSUE THREAD

**Issue by Nicd** [elixir-lang/elixir-lang.github.com#1174]
https://www.elixir-lang.org/ has a TLS certificate that has expired 40 days ago. The main site (without www) works fine.

**Comment by ericmj** [comment]
Hosting through github pages does not seem to support both apex and www domains when using https according to their docs if you look at the warning here [1], but it's pretty vague so I'm not really sure. I'm not sure why it worked in the past and stopped working now, maybe we should check with github support?

We do domain hosting through cloudflare so I think we can set up a www.elixir-lang.org => elixir-lang.org redirect with https support there. Wdyt @georgeguimaraes?

[1] https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

**Comment by georgeguimaraes** [comment]
>  I think we can set up a www.elixir-lang.org => elixir-lang.org redirect with https support there

It'll depend if Cloudfare's dns tool accepts redirects from https. @ericmj can you invite me to the Cloudfare account? I can take a look into that.

**Comment by ericmj** [comment]
I sent you an invite.

**Comment by georgeguimaraes** [comment]
@ericmj easier than I thought. There was already this rule (I think you wrote it) that I flipped on:

<img width="1030" alt="screen shot 2018-09-12 at 10 10 46" src="https://user-images.githubusercontent.com/2929/45427265-c86f5080-b674-11e8-97a6-a46640ca1843.png">

**Comment by georgeguimaraes** [comment]
Finally, got it!

For documentation purposes (and for any other Github Pages users dealing with https redirects), no Cloudfare Page Rules are needed.

We only need to make sure www.elixir-lang.org are proxyed through Cloudfare:
<img width="1033" alt="screen shot 2018-09-12 at 10 44 25" src="https://user-images.githubusercontent.com/2929/45429522-dd021780-b679-11e8-8622-3c01452eb25c.png">

So the orange cloud above means that Cloudfare will be a proxy. Gray cloud means that they are acting like a DNS server only.

And it's also worth mentioning that we are still using Cloudfare's free plan 😄
