### ISSUE TITLE
"Introduction to Mix" refers to "Environments" section as "next" incorrectly

### ISSUE THREAD

**Issue by link2xt** [elixir-lang/elixir-lang.github.com#1175]
[Running tests](https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#running-tests) section refers to [Environments](https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#environments) section as "next", but there is [Automatic code formatting](https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#automatic-code-formatting) section in-between.

**Comment by josevalim** [comment]
Fixed, thanks! Feel free to send pull requests too!
