### ISSUE TITLE
issues with elixir.csv 

### ISSUE THREAD

**Issue by sandyacse** [elixir-lang/elixir-lang.github.com#1184]
I am trying to use the Windows Installer to install Elixir but when I run the executable I get the following error: "Error downloading http://elixir-lang.org/elixir.csv failed. Setup cannot continue." Does anyone know what might be causing this error?

**Comment by josevalim** [comment]
I believe this is a duplicate of this one: https://github.com/elixir-lang/elixir-windows-setup/issues/14 - we can continue it there. Thanks!
