### ISSUE TITLE
Google Search box on docs page is leading to 404's

### ISSUE THREAD

**Issue by jdl** [elixir-lang/elixir-lang.github.com#1186]
**What I See**

The search box on the docs page appears to use Google, which commonly lists a missing page as the top hit.

Example

1. Go to https://elixir-lang.org/docs.html
2. Enter "get_in" in the search box.

As of today that's generating this search:
https://www.google.com/search?q=get_in&sitesearch=elixir-lang.org&submit=Search

The top result is:
https://elixir-lang.org/docs/stable/elixir/Access.html#!=/2

This page returns a 404.

**What I Expect To See**

The URL for the Access docs appears to be:
https://hexdocs.pm/elixir/Access.html

And Kernel is here:
https://hexdocs.pm/elixir/Kernel.html

I would expect either one to be returned.

**Comment by eksperimental** [comment]
@josevalim what happened with the github project that hosted the docs under /docs/ ? I cannot seem to find it

**Comment by ericmj** [comment]
@eksperimental The docs are hosted at https://hexdocs.pm/elixir.

I'm not sure why Google is showing the old docs in the search results because afaik they were removed quite a while ago. Can we set up redirect rules with Jekyll to redirect to the proper hexdocs page?

**Comment by eksperimental** [comment]
@ericmj Sure, I'm aware of that.
Actually I'm the one who carefully crafted the redirect pages to hexdocs.pm

**Comment by eksperimental** [comment]
I have a copy in case it got lost

**Comment by josevalim** [comment]
Thanks @jdl! I have updated the search to also include hexdocs results.

@eksperimental I did remove the docs repository because Google was supposed to remove the pages once they 404'ed. I have entered the Google Search Console and asked it to remove the old pages. Let's see if it will work now. Please keep your repo around in case it doesn't. Thanks! :)

**Comment by eksperimental** [comment]
What is the benefit of removing these redirects, other than if somebody is scraping the whole website....?
Regardless Google, there are a lot of sources that are still linking to the old location, I found it super useful to redirect to the exact page with even the hash function. 404 is one of the really big annoyances of the web. Hope we could turn this back as it was unless there are reasons I'm not aware of.

**Comment by eksperimental** [comment]
@josevalim  btw the docs are here: https://github.com/eksperimental/docs
