### ISSUE TITLE
No mention of @impl

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [elixir-lang/elixir-lang.github.com#1188]
Issue
------
When introducing behaviours one of the things I noticed was that there is no mention of the `@impl` tag. I would argue this is important as it helps people know that they are actually implementing the interface.

If I had found out about `@impl` by accident I would have been left in ignorance.

Affected page
----------
https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#behaviours

Possible solution
------------
In the parser examples, add the missing tag with a small explanation after:
```
defmodule YAMLParser do
  @behaviour Parser
   
  @impl Parser
  def parse(str), do: {:ok, "some yaml " <> str} # ... parse YAML
  @impl true
  def extensions, do: ["yml"]
end
```

Reference to @impl:
https://hexdocs.pm/elixir/master/Module.html#module-impl

**Comment by josevalim** [comment]
Agreed, can you please send a PR?

**Comment by Fl4m3Ph03n1x** [comment]
Working on it!
