### ISSUE TITLE
[Epub] Codes cut by margin page

### ISSUE THREAD

**Issue by matstavares** [elixir-lang/elixir-lang.github.com#1193]
For example, Elixir Getting Started Guide, 
page 3 bottom of the page, the [async-threads:10]...
page 4 top "Interactive Elixir (1.4.0) - press..........Enter for hel"
bother me only when I get to the page 10
"is_funciton(add, 2) #check if...."

**Comment by josevalim** [comment]
I think we should just trim down the code snippets. Nothing to change on epub itself.
