### ISSUE TITLE
asciinema video not available https://elixir-lang.org/getting-started/debugging.html

### ISSUE THREAD

**Issue by csisnett** [elixir-lang/elixir-lang.github.com#1224]
The asciinema video at https://elixir-lang.org/getting-started/debugging.html just above section 3: Debugger, is not available.  if the person who recorded it has a local copy we could upload it again.

**Comment by josevalim** [comment]
Hi @sickill, is there any chance those videos are still around and they can be linked to my account? I did not know they would get archived, sorry for the trouble. My account is: https://asciinema.org/~josevalim

**Comment by sickill** [comment]
Hey, sorry about that. Since they were not linked to an account I had no easy way to reach out to authors in questions. Worry not, they're still around and I'll recover them ASAP.

**Comment by sickill** [comment]
Fixed. I also assigned the other ones (from here https://elixir-lang.org/blog/2017/07/25/elixir-v1-5-0-released/) to your account.

**Comment by josevalim** [comment]
Awesome!!!!!! Thank you so much!!!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
