### ISSUE TITLE
Elixir logo  - Commercial use

### ISSUE THREAD

**Issue by AgaAgnieszkaBorcz** [elixir-lang/elixir-lang.github.com#1227]
What license Elixir Logo is under?

**Comment by josevalim** [comment]
Unfortunately there is no license for use until the trademark process has been completed. Only then  we will discuss and adopt a policy but it makes no sense to have one until we officially own the mark.

**Comment by AgaAgnieszkaBorcz** [comment]
No worries. Thank you @josevalim
