### ISSUE TITLE
Question: using `start` instead of `DynamicSupervisor`?

### ISSUE THREAD

**Issue by ignatiusreza** [elixir-lang/elixir-lang.github.com#1257]
Hiya!

I'm new to elixir and is currently reading through the "Getting Started" guide, and have question related to `DynamicSupervisor` (I hope this is the right place to ask?)..

On [this page](https://elixir-lang.org/getting-started/mix-otp/dynamic-supervisor.html), `DynamicSupervisor` tries to solve a problem caused by the following lines of codes:

```elixir
{:ok, pid} = KV.Bucket.start_link([])
ref = Process.monitor(pid)
```

in that, since links are bidirectional, crash in a bucket will crash the registry, and the added test proves that.. the tutorial then moves on with introducing `DynamicSupervisor` as the solution, but, if the issue is cause by using `start_link/1`, couldn't we also solve the problem by replacing it with `start/1`? as in:

```elixir
{:ok, pid} = KV.Bucket.start([])
ref = Process.monitor(pid)
```

with the respective `start/1` definition under `KV.Bucket` like so?

```elixir
def start(_options) do
  Agent.start(fn -> %{} end)
end
```

I tried this, and the test pass.. but, is there any downside to this approach? note that, I might be missing something entirely here.. :bowing_man:

**Comment by josevalim** [comment]
Yes, definitely, but you almost never use the `start` functions in practice, because processes are typically started as part of a supervision tree and you want to link the child process to the supervisor, mostly because if the supervisor terminates, you want its children to die too. So I think using a supervisor is closer to what you would see in real life.

Btw, about future questions, best places are either the ElixirForum or StackOverflow. :)

**Comment by ignatiusreza** [comment]
got it, sorry for the noise and thanks for the answer.. I thought that it might worth to add 1 or 2 sentence in the guide to clarify the point.. that's why I opened it as an issue..

**Comment by josevalim** [comment]
No problem! It is kind of trick because there may always be other possible
ways to solve the problem and if we were to discuss all of them, it would
take focus from the main discussion.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
