### ISSUE TITLE
state goal of page supervisor-and-application

### ISSUE THREAD

**Issue by mfrasca** [elixir-lang/elixir-lang.github.com#1274]
the first section of the page `supervisor-and-application` does not make clear what is the concrete goal of the page, except for a generic "we are going to learn about supervisors and also about applications".

The preceding pages have handled `Actor` and `GenServer`.  I must say, I asked myself the above question, started reading, after the first two or three sections, with this fat question mark in my head, I sort of lost track, and accelerated the pace until I found myself skimming to the end, and I did see where this new concept is put in relation to the previous ones.

Has it possibly to do with the closing "this is a bad idea" paragraph in the `GenServer` chapter?

**Comment by mfrasca** [comment]
c13847520e45739c0d45239c18852b001629928a

**Comment by josevalim** [comment]
Closing in favor of the PR.
