### ISSUE TITLE
1 = x freshly started iex

### ISSUE THREAD

**Issue by jediunixmaster** [elixir-lang/elixir-lang.github.com#1290]
➜  ~ iex
Erlang/OTP 21 [erts-10.0.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 1 = x
** (CompileError) iex:1: undefined function x/0

**Comment by josevalim** [comment]
Hi @jediunixmaster! This is working as expected. :) Were you expecting a different behaviour? If so, why?

**Comment by jediunixmaster** [comment]
in the 2nd code example under 'The match operator' I see this:
iex> 1 = x
1
iex> 2 = x
** (MatchError) no match of right hand side value: 1

**Comment by josevalim** [comment]
The section is meant to be continuous, the previous snippet defines `x`: https://elixir-lang.org/getting-started/pattern-matching.html#the-match-operator - so run them without shutting down and starting a new IEx.

But it is not problem at all and have fun learning Elixir!
