### ISSUE TITLE
Test failure by the end of Distributed Tasks section

### ISSUE THREAD

**Issue by jtrees** [elixir-lang/elixir-lang.github.com#1296]
Going through the guide from [here](https://elixir-lang.org/getting-started/mix-otp/distributed-tasks.html) I get a test failure (`kv_server_test.exs`) at the end.

It seems the routing table that gets overridden in the `setup` block in the tests isn't actually used by the application anywhere.

I was able to make the test pass like this:

```elixir
defmodule KV.Router do
  # ...

  def table do
    Application.get_env(:kv, :routing_table) || [
      {?a..?m, :foo@athena},
      {?n..?z, :bar@athena}
    ]
  end
end
```

**Comment by josevalim** [comment]
Ah, excellent! We have recently changed broken this chapter in 2, so this is a left-over. I have moved the discussion to the next chapter accordingly here: 8ce3519e16df34e08c98cff642731b41d6bb65f6 thanks!
