### ISSUE TITLE
`mix release foo` not working as instructed in the guides

### ISSUE THREAD

**Issue by jtrees** [elixir-lang/elixir-lang.github.com#1297]
I'm in the final chapter of the OTP guide and can't get releases working with mix.

```
$ pwd
/path/to/kv_umbrella

$ MIX_ENV=prod mix release foo  
** (Mix) The task "release" could not be found

$ mix --version
Erlang/OTP 22 [erts-10.4.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Mix 1.8.2 (compiled with Erlang/OTP 20)
```

Contents of `mix.exs` is as follows:

```elixir
defmodule KVUmbrella.MixProject do
  use Mix.Project

  def project do
    [
      apps_path: "apps",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      releases: [
        foo: [
          version: "0.0.1",
          applications: [kv_server: :permanent, kv: :permanent]
        ]
      ]
    ]
  end

  # Dependencies listed here are available only for this
  # project and cannot be accessed from applications inside
  # the apps folder.
  #
  # Run "mix help deps" for examples and options.
  defp deps do
    []
  end
end
```

**Comment by whatyouhide** [comment]
The guides refer to the latest version of Elixir, which is Elixir 1.9 (which was [released yesterday](https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released/)). Elixir 1.9 includes releases by default, so `mix release` will work using that version :).

**Comment by jtrees** [comment]
Has the latest version of the guides not been deployed yet? On [the introduction page](https://elixir-lang.org/getting-started/introduction.html) I still see a reference to "Elixir - Version 1.5.0 onwards".

**Comment by whatyouhide** [comment]
I think we can still say that the guides are for Elixir v1.5 onwards, but maybe specifically mention that the releases stuff requires Elixir 1.9? Wdyt?

**Comment by josevalim** [comment]
The Mix & OTP is a separate guide and at the beginning we say it depends on v1.9: https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html

The rationale is that we don't want to impose a high version on the introductory guides but we need to do so on the advanced ones. :)

**Comment by jtrees** [comment]
Oh I see. I missed that bit when I went back to look for it. It's a bit more prominent in the intro guide (black text, right at the beginning of the guide as opposed to light grey, several page scrolls down from the top).

Thanks anyway.

**Comment by josevalim** [comment]
@jtrees good point. we will move it up. :D
