### ISSUE TITLE
Fix "removes buckets on crash" test from dynamic-supervisor.md

### ISSUE THREAD

**Issue by ajhino** [elixir-lang/elixir-lang.github.com#1305]
```
test "removes bucket on crash", %{registry: registry} do
  KV.Registry.create(registry, "shopping")
  {:ok, bucket} = KV.Registry.lookup(registry, "shopping")

  # Stop the bucket with non-normal reason
  Agent.stop(bucket, :shutdown)
  assert KV.Registry.lookup(registry, "shopping") == :error
end
```

should be updated to use bucket instead of the registry string
```
test "removes bucket on crash", %{registry: registry} do
  KV.Registry.create(registry, "shopping")
  {:ok, bucket} = KV.Registry.lookup(registry, "shopping")

  # Stop the bucket with non-normal reason
  Agent.stop(bucket, :shutdown)
  assert KV.Registry.lookup(registry, bucket) == :error
end
```

See the fix @ https://github.com/ajhino/elixir-lang.github.com/commit/7576b11af35b50ff0f98d16ab4a6a752ebfc4f34

**Comment by josevalim** [comment]
@ajhino The argument to lookup is a string, you can see the "shopping" call two lines above. If you pass the bucket, than that particular entry was never added to the registry and it will always return error. If the test is not passing locally for you, it means you probably skipped or missed some other part of the code. :) You can see the original repo as a reference: https://github.com/josevalim/kv_umbrella

**Comment by ajhino** [comment]
I must be missing something around the supervisor. Seems like the `shopping` bucket is restarted or at least in an `:ok` state.  I'll compare against yours. Thanks!

```

  1) test removes bucket on crash (KV.RegistryTest)
     test/kv/registry_test.exs:28
     Assertion with == failed
     code:  assert KV.Registry.lookup(registry, "shopping") == :error
     left:  {:ok, #PID<0.180.0>}
     right: :error
     stacktrace:
       test/kv/registry_test.exs:34: (test)
```

**Comment by josevalim** [comment]
Perhaps this line? https://github.com/josevalim/kv_umbrella/blob/master/apps/kv/lib/kv/bucket.ex#L2

**Comment by ajhino** [comment]
I've got that included in my version. Checked against `supervisor.ex` to see if maybe there was something there, but no dice. I'm going through the diff with your branch, but there is a considerable delta since I'm not fully through the Mix/OTP tutorials. I'll keep digging around. It's probably something minor I left out.

**Comment by ajhino** [comment]
🔎 Found the issue - a 2 character oversight. I was calling `GenServer.cast` instead of `call` in `registry.ex`. Async vs sync was throwing off the test.

https://github.com/josevalim/kv_umbrella/blob/c3c3b8a0fac4e44f22ab9bb6322285c867b599ab/apps/kv/lib/kv/registry.ex#L34

The fix is included farther along in the docs at https://elixir-lang.org/getting-started/mix-otp/ets.html#race-conditions
