### ISSUE TITLE
Wrong Type explanation on tutorial

### ISSUE THREAD

**Issue by LuizBoina** [elixir-lang/elixir-lang.github.com#1378]
on [Basic types](https://elixir-lang.org/getting-started/basic-types.html) tutorial in the section that describe some Elixir types at the first box is saying that:

`iex> 1          # integer
iex> 0x1F       # integer
iex> 1.0        # float
iex> true       # boolean
iex> :atom      # atom / symbol
iex> "elixir"   # string
iex> [1, 2, 3]  # list
iex> {1, 2, 3}  # tuple`

0x1F isn't of type "integer" but the type hexadecimal

**Comment by josevalim** [comment]
Hi @LuizBoina. The type is still an integer, but we wrote it in an hexadecimal format. We can also write it using binaries and octals, they are all integers. :) Thanks!
