### ISSUE TITLE
Mentioning VSCode plugins and configuration

### ISSUE THREAD

**Issue by spapas** [elixir-lang/elixir-lang.github.com#1394]
When I needed to select a VSCode plugin for elixir I more or less stumbled upon two choices:

- mjmcloug.vscode-elixir with 151k installs 
- jakebecker.elixir-ls with 84k installs

Most people would consider the 1st one for installation. Unfortunately, that plugin hasn't been updated for more than a year meaning it won't support various features. 

Also, even with the 2nd one which is udpated before some days, VSCode needs some configuration to properly display leex files (syntax formatting).

I think it would be valuable for new users to recommend the correct plugin to use for VSCode and give some times on how to configure VSCode - maybe in an "editors" page that would also mention other editor / plugin configuration like vim or elixir for intellij idea or whatever other people use & recommend.

**Comment by josevalim** [comment]
Do you mean a page like this? https://github.com/elixir-lang/elixir/wiki/Code-Editor-Support

It is linked from the website home page. :)

**Comment by spapas** [comment]
Yes that's the one! Sorry I missed it!
