### ISSUE TITLE
getting-started contradicts itself - characters vs graphemes

### ISSUE THREAD

**Issue by malaire** [elixir-lang/elixir-lang.github.com#1420]
getting-started/basic-types.markdown says that `String.length/1` returns number of characters and number of graphemes. This can't be true so one of these claims is wrong:

> We can get the actual length of the string, based on the number of characters, by using the String.length/1 function:

> String.length/1 (for the number of graphemes in a string)

**Comment by josevalim** [comment]
Good catch. It is the number of graphemes clusters. For example, the e with the acute accent as two distinct entries would still be counter as length of 1. Can you please send a PR?

**Comment by malaire** [comment]
I'm still reading the guide so I don't know all the places which needs to be changed. For example I just noticed that `binaries-strings-and-char-lists` also says that `String.length/1` counts characters.

**Comment by malaire** [comment]
I'm closing this - Elixir/Phoenix docs have so many issues that I have no interest trying to fix them or comment about them.
