### ISSUE TITLE
Bug/Typo found in Getting Started: Typespecs and Behaviours

### ISSUE THREAD

**Issue by neenjaw** [elixir-lang/elixir-lang.github.com#1437]
Hello,

I encountered a bug/typo on the getting started website on the ["Typespecs and Behaviours"](https://elixir-lang.org/getting-started/typespecs-and-behaviours.html)  page under the ["Defining Custom Types"](https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#defining-custom-types) section. 

The code example reads:

```elixir
defmodule
   @typedoc """
   A 4 digit year, e.g. 1984
   """
   @type year :: integer
   
   @spec current_age(year) :: integer
   def current_age(year_of_birth), do: # implementation
end
```

As you can see, it seems to be missing a name for the module and the opening `do` for the `do..end`. 

I would be happy to open a PR to fix this if it would help.  

Was there previously an intended name for this module?

**Comment by josevalim** [comment]
We can call it Person or Age or Birthday. :) Your call!
