### ISSUE TITLE
getting started: basic types: linked lists: instructions on how to prevent ascii conversion with a list of integers?

### ISSUE THREAD

**Issue by jtagcat** [elixir-lang/elixir-lang.github.com#1444]
https://elixir-lang.org/getting-started/basic-types.html#linked-lists
`Sometimes you will create a list and it will return a value in single quotes. For example:`
If my code receives different data on a future run, I would quite like to be sure, that the program doesn't suddenly get text.

I would suggest including 'how to ensure that this doesn't happpen'.

**Comment by josevalim** [comment]
It doesn’t suddenly become text. It is always a list, it is just that we print on the terminal differently if it looks like text. But they are the same. A couple paragraphs below we show the “i” helper, that shows both textual and raw representation. Thanks!
