### ISSUE TITLE
Project compilation section version update

### ISSUE THREAD

**Issue by z82n** [elixir-lang/elixir-lang.github.com#1470]
`Mix.env` in the docs, in latest version it is `Mix.env()`

https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#project-compilation

The mix.exs file in 1.11 now looks like this:

```
defmodule KV.MixProject do
  use Mix.Project

  def project do
    [
      app: :kv,
      version: "0.1.0",
      elixir: "~> 1.11",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
    ]
  end
end

```

**Comment by ericmj** [comment]
Please send a PR that updates the example. https://github.com/elixir-lang/elixir-lang.github.com/blob/master/getting-started/mix-otp/introduction-to-mix.markdown#project-compilation

**Comment by z82n** [comment]
https://github.com/elixir-lang/elixir-lang.github.com/pull/1471
