### ISSUE TITLE
Getting started guide might have incorrect information about Float.round/2

### ISSUE THREAD

**Issue by cschmatzler** [elixir-lang/elixir-lang.github.com#1482]
On [Basic types](https://elixir-lang.org/getting-started/basic-types.html), teaching about function arity, there is the following paragraph:  

> `round/1` identifies the function which is named round and takes 1 argument, whereas `round/2` identifies a different (nonexistent) function with the same name but with an arity of 2.

While it is true that `Kernel.round/2` does not exist, it does exist as `Float.round/2` on the type itself, see [here on hexdocs](https://hexdocs.pm/elixir/Float.html#round/2).
To me as a beginner, this is somewhat confusing. Is the guide supposed to mention only the function exposed by the kernel? If so, adding a reference that it does exist somewhere else might be useful.

**Comment by josevalim** [comment]
Good point. I will change it to `abs/1` which wouldn't have such issues. Thank you!

**Comment by josevalim** [comment]
I actually went with trunc, since we just used it before too!
