### ISSUE TITLE
Documentation doesn't explain scoping rules in Elixir

### ISSUE THREAD

**Issue by a8t** [elixir-lang/elixir-lang.github.com#1526]
Hi, let me know if I should move or add this issue to another repo.

I think it would be good if the Getting Started guide included an explanation of scoping rules in Elixir.

This resource is quite comprehensive: https://elixir-lang.readthedocs.io/en/latest/technical/scoping.html
It appears that no comparable 'official' resource is available. To me, this is an oversight – variable scoping seems like a fundamental aspect of a language.

Should we add some of that content into the Getting Started?

(cc @axelson with whom this came up in conversation)

**Comment by josevalim** [comment]
I would say scoping is outside of a _Getting Started_ guide and more of an advanced topic. I believe we mention the rules as we introduce the constructs but we could have a unified  guide either in the meta programming guides or in Elixir detailed pages.

**Comment by a8t** [comment]
Actually yes, as you mentioned, it's mentioned briefly here: https://elixir-lang.org/getting-started/try-catch-and-rescue.html#variables-scope

**Comment by josevalim** [comment]
Yes, I was sure we mentioned it on if/unless too. I think try/catch could be rewritten though, it behaves the same as any other construct and it is written as if it wasn’t.

**Comment by josevalim** [comment]
So I think I will improve the docs for try/catch and close it. :) thanks for the feedback!

**Comment by a8t** [comment]
Great, thanks José!
