### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by trkoch** [elixir-lang/elixir-lang.github.com#1541]
Any objections to introducing a dark mode of the site? This would be especially welcome for reading the getting started guide at night. Ideally switch by default, but allow to toggle manually. Already implemented for the docs (https://github.com/elixir-lang/ex_doc/pull/491).

**Comment by trkoch** [comment]
For now, using an extension to automatically invert colors is a viable workaround (https://github.com/darkreader/darkreader). A fine-tuned human-generated style would be preferable, of course.

**Comment by josevalim** [comment]
If someone submits a pull request, we would gladly accept it, but not in our plans at the moment :)
