### ISSUE TITLE
Problem with `KV.RouterTest` with two nodes on same machine

### ISSUE THREAD

**Issue by Gobljn** [elixir-lang/elixir-lang.github.com#1549]
I read and follow the mix and OTP guide and I find some problems during the run of `KV.RouterTest` describe here: 
https://elixir-lang.org/getting-started/mix-otp/distributed-tasks.html#routing-layer

The problem occurs only if the nodes used for the test are on the same machine because there is a conflict on `:gen_tcp.listen(...)` port.
This is the error obtained:
```
[error] Task #PID<0.180.0> started from KVServer.Supervisor terminating
** (MatchError) no match of right hand side value: {:error, :eaddrinuse}
    (kv_server 0.1.0) lib/kv_server.ex:16: KVServer.accept/1
    (elixir 1.12.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.87249467/0 in KVServer.Application.start/2>
    Args: []
 ```
 
 Maybe a warning could be added to the guide?
 Let me know your opinion, in a positive case I'm happy to do a PR to add it.

**Comment by josevalim** [comment]
I believe we talk about making the port configurable later on. :) when discussion application configuration.

**Comment by Gobljn** [comment]
Oh sorry, you are right!
I open this issue without reading the last chapter 😓 
Thank you :D
