### ISSUE TITLE
Ubuntu installation instructions out-of-date?

### ISSUE THREAD

**Issue by Odaeus** [elixir-lang/elixir-lang.github.com#1575]
Hi,

I just upgraded to Ubuntu 21.10 ("Impish") and noticed that the recommended instructions to use Erlang Solutions packages don't work because the packages don't support Ubuntu versions after 20.04 "Focal" (see [dist listing](http://binaries.erlang-solutions.com/debian/dists/)).

The installation of the `erlang-solutions_2.0_all.deb` package succeeds but it blindly puts "impish" in the Apt source file, which causes `apt update` to output:
```
Ign:1 http://binaries.erlang-solutions.com/debian impish InRelease
Err:2 http://binaries.erlang-solutions.com/debian impish Release
  404  Not Found [IP: 18.66.2.39 80]
[...]
E: The repository 'http://binaries.erlang-solutions.com/debian impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Ubuntu 21.10 has [Erlang version 23.2.6](https://packages.ubuntu.com/impish/erlang), which is relatively up-to-date (latest is 24.1.4), and [Elixir 1.10.3](https://packages.ubuntu.com/impish/elixir) which is a bit old (latest 1.12).

Manually editing `/etc/apt/sources.list.d/erlang-solutions.list` to replace `impish` with `focal` still works to install the latest Erlang and Elixir packages. I don't know if at some point (binary lib compatibility?) it won't.

Should the instructions on the site be amended to include this workaround? Or it could be split into two sets of instructions, where `apt-get install elixir` on plain Ubuntu will install a relatively recent version but if you want the very latest then follow alternate steps?

**Comment by josevalim** [comment]
Thanks for the report! I would say the best would be is to reach out to Erlang Solutions to make the new versions available. Could you please do that? Meanwhile your report can help users. Thank you!

**Comment by Odaeus** [comment]
👍🏻  I've sent them an email.

**Comment by Odaeus** [comment]
Following up after a month. I didn't receive a reply to my email yet but after checking today I found a new "impish" directory with some files. It seems incomplete so I guess it's in progress.
http://binaries.erlang-solutions.com/ubuntu/dists/impish/

**Comment by KelvinHu** [comment]
Sorry for the necro but I wanna do a followup following @Odaeus.

The step for installing`esl-erlang` is no longer valid as it appears that Erlang Solutions split Erlang into multiple smaller subsets. 

When attempting to install `erlang` or `elixir` I get file mismatch errors; APT suggests that a mirror sync is possibly in progress so I'll check in again after a few days.

I've attached the results of running: `sudo apt install elixir`

[result.txt](https://github.com/elixir-lang/elixir-lang.github.com/files/8038448/result.txt)

**Comment by usama-asfar** [comment]
any update?

**Comment by Odaeus** [comment]
I never received a reply from ESL and the Impish release directory is unchanged since 3rd Dec 2021. It's missing "arm64" support for me. I've started switching to the ASDF manager.

**Comment by KelvinHu** [comment]
@usama-asfar Sorry for not posting an update, but like @Odaeus said there hasn't been any change. My current suspicion is that they're targeting for LTS distributions instead of the latest point-releases.

**Comment by darshandzend** [comment]
Same error on 22.04 LTS:

```
E: The repository 'http://binaries.erlang-solutions.com/debian jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by BatmanAoD** [comment]
Posting here just in case anyone else is struggling to install Erlang on Ubuntu-on-WSL.

I was able to download the `.deb` file for my distribution, then use `sudo apt install ./<file>` to install it (this installs dependencies as well). Unfortunately, I then ran into what appears to be an unrelated Nvidia driver issue, which I had to fix in the host (Windows) system: https://github.com/microsoft/WSL/issues/5663

After following the recommended steps there to fix the `libcuda` symlinks and rebooting WSL, everything seems to be working.

**Comment by jeffwidman** [comment]
In http://binaries.erlang-solutions.com/ubuntu/dists/jammy/, I see a binary file but no release file.

**Comment by Odaeus** [comment]
There is still no change here almost a year later. It's not hard to imagine that having installation instructions that don't work on the Elixir home page is having a negative effect, possibly deterring newcomers to the language.

I would suggest amending the instructions to use the Ubuntu package by default, as it's better than nothing, despite being a few versions out of date (1.12.2 as of writing). Personally I use _asdf_, which I see is already one of the recommendations "if you want the latest version".

I'm happy to make this small change to the instructions if requested!

**Comment by josevalim** [comment]
A PR is welcome!

**Comment by bluespiderdev** [comment]
> Hi,
> 
> I just upgraded to Ubuntu 21.10 ("Impish") and noticed that the recommended instructions to use Erlang Solutions packages don't work because the packages don't support Ubuntu versions after 20.04 "Focal" (see [dist listing](http://binaries.erlang-solutions.com/debian/dists/)).
> 
> The installation of the `erlang-solutions_2.0_all.deb` package succeeds but it blindly puts "impish" in the Apt source file, which causes `apt update` to output:
> 
> ```
> Ign:1 http://binaries.erlang-solutions.com/debian impish InRelease
> Err:2 http://binaries.erlang-solutions.com/debian impish Release
>   404  Not Found [IP: 18.66.2.39 80]
> [...]
> E: The repository 'http://binaries.erlang-solutions.com/debian impish Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```
> 
> Ubuntu 21.10 has [Erlang version 23.2.6](https://packages.ubuntu.com/impish/erlang), which is relatively up-to-date (latest is 24.1.4), and [Elixir 1.10.3](https://packages.ubuntu.com/impish/elixir) which is a bit old (latest 1.12).
> 
> Manually editing `/etc/apt/sources.list.d/erlang-solutions.list` to replace `impish` with `focal` still works to install the latest Erlang and Elixir packages. I don't know if at some point (binary lib compatibility?) it won't.
> 
> Should the instructions on the site be amended to include this workaround? Or it could be split into two sets of instructions, where `apt-get install elixir` on plain Ubuntu will install a relatively recent version but if you want the very latest then follow alternate steps?

I run this command "sudo nano /etc/apt/sources.list.d/erlang-solutions.list" but there aren't any text "impish" or "focal". How can I do now?

**Comment by josevalim** [comment]
Try using asdf to manage Erlang and Elixir. It should give you quite more flexibility. The install guides should mention it too. :)

**Comment by bluespiderdev** [comment]
Thank you for your attention
