### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by robsonpeixoto** [elixir-lang/elixir-lang.github.com#1609]
The http://elixir-lang.org/ is not redirecting to https://elixir-lang.org/. It's is not a problem, but it will show a "Not Secure" alert on the URL.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/124390/167831433-43ee5242-e0da-44e7-8240-bc26866288f9.png">
<img width="194" alt="image" src="https://user-images.githubusercontent.com/124390/167831818-59cea972-17b5-4df9-a83e-6eb2a5bb94cc.png">

Is possible to enable a https enforcement following this documetation: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by josevalim** [comment]
Thank you, I have enabled redirection and it should propagate soon!
