### ISSUE TITLE
Can section on supervisors and genservers be simplified?

### ISSUE THREAD

**Issue by wktdev** [elixir-lang/elixir-lang.github.com#1645]
I understand conceptually the idea behind GenServers and Supervisors and I learned them using the following tutorial:
https://www.culttt.com/2016/09/07/working-supervisors-elixir/

The examples in the tutorial are clear and I understand them. Albeit although some of the syntax is outdated, I figured out how to updated it. I can understand the connections between the different code pieces, client and server code.

I would like to learn using the elixir-lang docs as they contain very important ideas that the above tutorial is omitting.  However, trying to learn GenServers/Supervisors using the Documentation just feels like a wash of overcomplicated syntax and jargon. I honestly feel too stupid to understand it and I feel penalized further for admitting it. 

https://elixir-lang.org/getting-started/mix-otp/genserver.html

The problem from my point of view is thee are no simple, bare-minimum self-explaining, completed code that I can paste into my editor, compile and run that I can play with and use to learn. 

Portions of the example code do not specify what file they are referenced from and I can't tell if the instructions are inferring that we are to update code, just read or create new files.

I am confused as to why GenServers need to be **named** to work with Supervisors. Are we using the developer-created registry to work around the :atom limit? If so why not just reference the GenServer by pid ? Am I wrong? I don't even know if I'm asking a legitimate question. 

From my point of view, it seems like the section on GenServers and Supervisors is a cluttered bottleneck that should be simplified and take more time to explain itself. I don't know exactly what that means but I do know I feel lost. I would chalk it up to my own incompetence but reading the tutorial at the top of the page in place of the docs, everything was perfectly clear. 

Maybe the doc writers could write a tutorial on the "side" that mirrors the style I referenced in the tutorial. Maybe it could act as an addendum to the main docs on the topic.

**Comment by josevalim** [comment]
Hi @wktdev! Thanks for the feedback.

We are glad you found an article that clicked. We will keep listening to feedback and see else we can improve but it is expected some articles make better sense to some and others to others. :)

what makes our article trickier is that it needs to fit into the system we are building, so there are more moving parts, but we also got feedback that building a whole system is helpful. The good news is that there are options and I wouldn’t necessarily aim to normalize around one. The GenServer and Supervisor docs themselves may provide a more isolated introduction as well. :)

**Comment by josevalim** [comment]
> However, trying to learn GenServers/Supervisors using the Documentation just feels like a wash of overcomplicated syntax and jargon.

Just to clarify, are you building the whole project and now arrived to the GenServer section or jumped right into it?

> If so why not just reference the GenServer by pid ? 

The challenge is that we need to map a bucket name (which will be given by a client) to a pid.

—-

Don’t be discouraged to ask questions, it is part of the learning process. I also recommend the communities on Slack, ElixirForum and Discord for general assistance. :)
