### ISSUE TITLE
Link to exenv repo seems to be broken/project may no longer exist

### ISSUE THREAD

**Issue by jordan-king** [elixir-lang/elixir-lang.github.com#1649]
Hi there 👋 The [install.markdown](https://github.com/elixir-lang/elixir-lang.github.com/blob/main/install.markdown?plain=1#L144) page lists `exenv` as one of the options for compiling with a version manager; however, the link is dead/the repo doesn't seem to exist anymore. I'll happily raise a PR to remove it, but it seems weird enough that it just _disappeared_ that I figured I'd start by raising an issue first.

**Comment by josevalim** [comment]
I am pretty sure things consolidated around kiex/kerl/asdf, so a PR to remove the link is very welcome. :) Thank you!
