### ISSUE TITLE
Escaping section is outdate 

### ISSUE THREAD

**Issue by manhtranlinh** [elixir-lang/elixir-lang.github.com#1670]
https://elixir-lang.org/getting-started/meta/quote-and-unquote.html#escaping

**Comment by josevalim** [comment]
What is out of date? Can you please provide a pull request?

**Comment by manhtranlinh** [comment]
Sorry, I had a mistake.  I did not intent to the line "However, such values can be expressed as a quoted expression". So I thought that the document is outdated with Elixir 1.14.0.
