### ISSUE TITLE
Bad link in "Mix and OTP" EPUB

### ISSUE THREAD

**Issue by siiky** [elixir-lang/elixir-lang.github.com#1686]
The ["Mix and OTP" EPUB](https://repo.hex.pm/guides/elixir/mix-and-otp.epub) links to `http://elixir-lang.org/cheatsheets/gen-server.pdf` instead of `https://elixir-lang.org/downloads/cheatsheets/gen-server.pdf`. The [website page](https://elixir-lang.org/getting-started/mix-otp/genserver.html) has the correct URL.

https://github.com/elixir-lang/elixir-lang.github.com/blob/b2d913f375e93a07e1f2bd90560365146a3f59e0/getting-started/mix-otp/genserver.markdown?plain=1#L330

**Comment by josevalim** [comment]
We are moving the guides to Elixir and this will be automatically fixed as part of the process. :)
