### ISSUE TITLE
IO and the file system

### ISSUE THREAD

**Issue by rhcarvalho** [elixir-lang/elixir-lang.github.com#1687]
The second paragraph in [Getting Started: IO and the file system](https://elixir-lang.org/getting-started/io-and-the-file-system.html#:~:text=We%20had%20originally%20sketched%20this%20chapter%20to%20come%20much%20earlier%20in%20the%20getting%20started%20guide.%20However%2C%20we%20noticed%20the%20IO%20system%20provides%20a%20great%20opportunity%20to%20shed%20some%20light%20on%20some%20philosophies%20and%20curiosities%20of%20Elixir%20and%20the%20VM.) reads:

> We had originally sketched this chapter to come __much earlier__ in the getting started guide. __However, we noticed the IO system provides a great opportunity__ to shed some light on some philosophies and curiosities of Elixir and the VM.

I have the impression what was meant was __much later__ instead of __much earlier__, as otherwise the contrast with "however" sounds weird. The overall sentence gives me the intuition that this section comes now instead of later to teach me something worthwhile.

Could someone confirm or reject my reasoning? I could send a patch in the positive case.

**Comment by josevalim** [comment]
It is meant to be written as is. We want to use the chapter on IO to explore more complex topics, so it comes later. But, nowadays, I think we can just remove this sentence anyway.

**Comment by rhcarvalho** [comment]
Thanks @josevalim! Reading again I understood it: originally it would have come earlier, but it's been "delayed" because it has more advanced ideas that wouldn't fit well much earlier in the guide.

**Comment by josevalim** [comment]
If you want to send a PR either removing or improving it, it will be welcome. :) Your call!
