### ISSUE TITLE
Debian flavors alternative installation

### ISSUE THREAD

**Issue by naxels** [elixir-lang/elixir-lang.github.com#1704]
Hi all,

It took me a while in order to figure out how to get the latest Erlang / Elixir versions working on Ubuntu LTS 22.04
while not having to deal with the OS versions and / or compile the latest versions myself each time.

Finally I found a great resource provided by the community as listed here in Method 1:
https://itsfoss.com/install-erlang-ubuntu/

I've been able to successfully follow this guide with 1 change to install Elixir which automatically installs Erlang:

> sudo add-apt-repository ppa:rabbitmq/rabbitmq-erlang
> sudo apt update
> sudo apt install elixir

I think it would be a great help to newcomers to have this option available as well, likely mentioning that the versioned approach is preferred.

I wanted to make a PR but don't know exactly where to put this in the Installing Elixir page:
https://elixir-lang.org/install.html#gnulinux

as there are several Debian flavors like Ubuntu and you don't want to list this everywhere.

Thank you for considering!

**Comment by josevalim** [comment]
I think we can list it as an alternative for Debian, since the Elixir package is not always up to date. :) PRs welcome!

**Comment by naxels** [comment]
I might be using the PPA too short then haha, even Elixir 1.15.4 is already available currently:
https://launchpad.net/~rabbitmq/+archive/ubuntu/rabbitmq-erlang

Will work on a PR :)
