### ISSUE TITLE
Add a bit more detail about erlang modules and elixir atoms

### ISSUE THREAD

**Issue by yasoob** [elixir-lang/elixir-lang.github.com#1722]
Hi guys! I am just now getting started with Elixir. The guide on the website is very approachable and informative. I have a suggestion though. While going through the [Erlang Libraries](https://github.com/elixir-lang/elixir-lang.github.com/blob/main/getting-started/erlang-libraries.markdown) section, I got a bit confused. The Erlang modules are regular atoms and they behave like atoms and only when we try calling a function over them do we use them as Erlang modules.

This bit is not mentioned clearly in the docs. I had to do some research to clear up this confusion. I am not an Erlang or Elixir expert so I am not sure what the proper wording should be for this but I do believe it will be beneficial for future readers if this is mentioned in the guide.

References: https://tylerpachal.medium.com/why-do-erlang-modules-look-like-atoms-in-elixir-9fb2f964dd2b

**Comment by josevalim** [comment]
Thank you. Those guides have been moved to Elixir and I pushed a fix there.

**Comment by yasoob** [comment]
Well in that case, can we also change the HTML templates so that this link at the bottom navigates to elixir rather than here? I came here through that link :)

Ref:
<img width="800" alt="image" src="https://github.com/elixir-lang/elixir-lang.github.com/assets/3696393/d59abd65-282d-43f6-91ef-09d28c00ff76">

**Comment by josevalim** [comment]
It will change once we deploy the new version. For now, arriving here is still the best way, so no worries!
