### ISSUE TITLE
Should there be a PagerDuty case study?

### ISSUE THREAD

**Issue by vlymar** [elixir-lang/elixir-lang.github.com#1732]
I recently came across these posts and talks from PagerDuty. It looks like they've been using Elixir in interesting ways for critical services for years.

- https://www.youtube.com/watch?v=-d2NPc8cEnw
- https://www.pagerduty.com/eng/elixir-stateful-services/
- https://www.pagerduty.com/blog/elixir-at-pagerduty/
- https://www.youtube.com/watch?v=0CAE1N6Ik6A

Seems like a great opportunity for a case study! PagerDuty is a household name amongst engineers (at least in my niche). I don't work at PagerDuty but if there's anything I can do to help let me know. I could try to find someone who'd be willing to talk to the Elixir team for a case study. 

If this is the wrong place for this post, or this has already been thought of feel free to close this ticket.

**Comment by josevalim** [comment]
I do have them in my list of companies to add as cases but generally speaking I handle this privately, otherwise it is easy to get overwhelmed with requests. Thanks for the long though!
