### ISSUE TITLE
Broken link/redirect after #1738

### ISSUE THREAD

**Issue by rhcarvalho** [elixir-lang/elixir-lang.github.com#1740]
I noticed `mix help phx.new` (with Phoenix 1.7.10) links to https://elixir-lang.org/getting-started/mix-otp/dependencies-and-umbrella-apps.html#umbrella-projects

The link as-is is broken:  

![image](https://github.com/elixir-lang/elixir-lang.github.com/assets/88819/b174724a-cdf1-4209-8ccc-a3181034c76f)

I noticed if I remove the trailing part of the URL, then https://elixir-lang.org/getting-started/mix-otp/ redirects to https://hexdocs.pm/elixir/1.16/introduction-to-mix.html.

The new place is: https://hexdocs.pm/elixir/1.16/dependencies-and-umbrella-projects.html#umbrella-projects

I'll send an update to Phoenix, but thought of reporting here since the redirect logic may be missing some valid URLs.

**Comment by rhcarvalho** [comment]
Ah, I think the file was renamed: 

```diff
- dependencies-and-umbrella-apps.html
+ dependencies-and-umbrella-projects.html
```

**Comment by bdanklin** [comment]
Further to the above, there are various links scattered around the internet pointing to the old guides that cannot be updated. eg [this answer on stackoverflow](https://stackoverflow.com/questions/32104419/task-could-not-be-found-for-custom-mix-task) which points at https://elixir-lang.org/getting-started/modules.html#scripted-mode

I'm not sure if there is a way to set up redirects to the new guides in the docs but I figure that being something that would disproportionately affect newcomers and novice users it was worth at least mentioning.

**Comment by josevalim** [comment]
We did setup redirects. But sometimes the old pages had redirects themselves and those were lost along the way. It is trivial to add them back, and I did so for both reported here. If you find more, let me know (or send a PR, it is easy, see 89e644965c577349321acdc605b48606b693c558). Thanks!
