### ISSUE TITLE
kv-observer.png not found in docs for Elixir v1.18.0+

### ISSUE THREAD

**Issue by dsqrt4** [elixir-lang/elixir-lang.github.com#1785]
The _Supervising dynamic children / Observer_ section of the Mix/OTP guide embeds the image [`kv-observer.png`](https://github.com/elixir-lang/elixir-lang.github.com/blob/main/images/contents/kv-observer.png).

Starting with v1.18.0, the image is no longer found:
- [v1.17.3](https://hexdocs.pm/elixir/1.17.3/dynamic-supervisor.html#observer): works
- [v1.18.0](https://hexdocs.pm/elixir/1.18.0/dynamic-supervisor.html#observer): not found
- [v1.18.1](https://hexdocs.pm/elixir/1.18.1/dynamic-supervisor.html#observer): not found
- [current (v1.18.1)](https://hexdocs.pm/elixir/dynamic-supervisor.html#observer): not found

The image source is `assets/kv-observer.png` in all versions.

Unfortunately I don't see where this issue is coming from, so I cannot provide a PR for it.
However I'll gladly do so with some guidance if that helps at all.

**Comment by josevalim** [comment]
Thank you for the report. The image was accidentally removed from the docs and I have added it back. :)
