### ISSUE TITLE
Add library design principles file

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir-lang.github.com#310]
As seen here: http://library.elm-lang.org/DesignGuidelines.html

**Comment by whatyouhide** [comment]
I'd be happy to help but the provided link is dead :(.

**Comment by eksperimental** [comment]
https://lumi.do/p/df4061ed2e8573d4e290c433962d171968d5831628124b768beedbcb01459d05/

**Comment by eksperimental** [comment]
ok. this is the new link:
http://package.elm-lang.org/help/design-guidelines

**Comment by josevalim** [comment]
I am assigning this task to me because there are large considerations we should do when creating this page! Thanks for the updated link.
