### ISSUE TITLE
Mix and OTP guide, part 6: Need to update KV.Supervisor sooner

### ISSUE THREAD

**Issue by ccblaisdell** [elixir-lang/elixir-lang.github.com#317]
Hi, I've been working through the Mix and OTP guide, and I *think* I've uncovered a problem. In part 6.1 of the Mix and OTP guide, ETS as a cache, we change KV.Registry.start_link/2 to take an extra parameter, the ets table name.

```elixir
def start_link(table, event_manager, buckets, opts \\ []) do
  # 1. We now expect the table as argument and pass it to the server
  GenServer.start_link(__MODULE__, {table, event_manager, buckets}, opts)
end
```

We see this text a few paragraphs down:

> The changes we have performed above have definitely broken our tests. For starters, there is a new argument we need to pass to KV.Registry.start_link/3. Let's start amending our tests in test/kv/registry_test.exs by rewriting the setup callback:

But following the next set of instructions doesn't fix the tests, because we haven't updated KV.Supervisor to pass the new param. Instead, we continue to get this output every place we are supposed to see passing or failing tests, until we finally change the supervisor way down at the bottom of part 6.2.

```elixir
➜  kv git:(master) ✗ mix test
Compiled lib/kv.ex
Compiled lib/kv/supervisor.ex
Generated kv.app

=INFO REPORT==== 12-Aug-2014::17:40:58 ===
    application: kv
    exited: {{shutdown,
                 {failed_to_start_child,'Elixir.KV.Registry',
                     {'EXIT',
                         {undef,
                             [{'Elixir.KV.Registry',start_link,
                                  ['Elixir.KV.EventManager',
                                   [{name,'Elixir.KV.Registry'}]],
                                  []},
                              {supervisor,do_start_child,2,
                                  [{file,"supervisor.erl"},{line,314}]},
                              {supervisor,start_children,3,
                                  [{file,"supervisor.erl"},{line,297}]},
                              {supervisor,init_children,2,
                                  [{file,"supervisor.erl"},{line,263}]},
                              {gen_server,init_it,6,
                                  [{file,"gen_server.erl"},{line,306}]},
                              {proc_lib,init_p_do_apply,3,
                                  [{file,"proc_lib.erl"},{line,239}]}]}}}},
             {'Elixir.KV',start,[normal,[]]}}
    type: temporary
** (Mix) Could not start application kv: KV.start(:normal, []) returned an error: shutdown: failed to start child: KV.Registry
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function: KV.Registry.start_link/2
            (kv) KV.Registry.start_link(KV.EventManager, [name: KV.Registry])
            (stdlib) supervisor.erl:314: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:297: :supervisor.start_children/3
            (stdlib) supervisor.erl:263: :supervisor.init_children/2
            (stdlib) gen_server.erl:306: :gen_server.init_it/6
            (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
```

Of course, I'm still learning the basics and might have just missed something obvious. Don't come down on me too hard if that's the case :)

**Comment by dbbrian** [comment]
I'm probably not the first one to come up with it, but I have a (terrible) hack for that... Markdown allows HTML, and comments are valid HTML, so with something like this in the `.markdown` file:

```markdown
<!-- data-emphasize-lines: 2, 4 -->
```elixir
defmodule Math do
  def sum(a, b) do
    a + b
  end
end
```

And [a few lines of JS and CSS](https://gist.github.com/dbbrian/40f009b9a133d50457dc), make this:

![before](https://cloud.githubusercontent.com/assets/188809/8037404/d3712bca-0dfd-11e5-87d6-01b42009fed9.png)

Looks like this:

![after](https://cloud.githubusercontent.com/assets/188809/8037425/e84dd7be-0dfd-11e5-8201-521ed7aed9f8.png)

I may have used that kind of trick in prod. to embed some Google Maps things... 😁

**Comment by sircharleswatson** [comment]
@dbbrian That's a good idea and I think it'd make things much clearer. is there any way to specify a different color maybe?

**Comment by dbbrian** [comment]
@sircharleswatson Thanks! And sure, the CSS can be tweaked, or the code could be extended to support multiple `data-` attributes.

Or something really dirty like this:

```markdown
<!-- data-emphasize-lines: 2#123456, 4#abcdef -->
```elixir
defmodule Math do
  def sum(a, b) do
    a + b
  end
end
```

It's just an hacky way to get metadata to the client, once you have it you can parse it, and use it however you need.

/cc @josevalim
