### ISSUE TITLE
Create a "directory listing" page for http://elixir-lang.org/docs/stable/ and http://elixir-lang.org/docs/master/ 

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#386]
I find it a bit unintuitive to have an ERROR 404 page when visiting: http://elixir-lang.org/docs/stable/ and http://elixir-lang.org/docs/master/

I think it should be helpful to list all the projects under that folder.

**Comment by eksperimental** [comment]
I have submitted a pull request to /docs

https://github.com/elixir-lang/docs/pull/5

let me know whether it works or not, as i wasn't able to set up a gh-page in my respository.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
