### ISSUE TITLE
Getting started docs do not introduce the pipe operator

### ISSUE THREAD

**Issue by IdahoEv** [elixir-lang/elixir-lang.github.com#395]
Working through as a beginner (and using it as a reference), I notice that the |> operator is never actually explained in "Getting Started".  It first appears  in example code in 10.1 "Eager vs. Lazy", where it is used without explanation or introduction.

I would like to insert a new section to introduce the pipe operator.  If you're okay with this proposal I'll get writing and issue a PR. 

My instinct would be to put the new section between 5 and 6, after other basic language structures but before data types. It would probably also be okay later on. It would have two subsections:

### subsection 1: pipe operator and method chaining
introduce the operator and explain how it improves readability over f4(f3(f2(f1(arg))))

### subsection 2: chainable methods
Introduce this stylistic / semantic tradeoff:

* Erl-style functions that return { :ok | :error, value }, which are useful for handling error cases with pattern matching
* Simple return functions that just return value, which are easier to use with |>.    

Then explain how the Elixir stdlib sometimes introduces both variants for this reason (E.g. Dict.fetch/2 and Dict.fetch!/2)

**Comment by whatyouhide** [comment]
I think this can be closed since #411 has been merged :).
