### ISSUE TITLE
Section Getting Started - Basic Type - String, need more info on how to mak it work on windows 

### ISSUE THREAD

**Issue by JRBourque** [elixir-lang/elixir-lang.github.com#414]
I'm trying to follow the Getting Started guide and was unable to work with UTF-8  characters , I've tried  with the standard windows command prompt  Git Bash and conemu  and i was not able to make Elixir print the accented characters with the default windows encoding i get the following 
```
iex(1)> "testé"
** (UnicodeConversionError) invalid encoding starting at <<130, 34, 10>>
    (elixir) lib/string.ex:1350: String.to_char_list/1
```
and using chcp 65001
```
C:\>chcp 65001
Page de codes active : 65001

C:\>iex
Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> "test é"

nil
```

i'm using windows 8.1 and i was able to reproduce the issue with the windows command prompt, Git Bash and conEmu 

Thanks

**Comment by josevalim** [comment]
Perfect, thank you for the information and the report!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by josevalim** [comment]
Fixed, thank you!
