### ISSUE TITLE
 Typos: Chapter 20

### ISSUE THREAD

**Issue by dpdawson** [elixir-lang/elixir-lang.github.com#430]
20.1.1
In the first paragraph, "returns a float" should be "returns an integer".

20.1.2
In the second paragraph, "RudeCalculator" should be "LousyCalculator".

**Comment by whatyouhide** [comment]
So sorry :disappointed: Opened a PR with a fix. Again, I'm sorry! I'll be more careful in the future.

**Comment by josevalim** [comment]
Don't be sorry! I make types and mistakes like this all the time. Thanks everyone!
