### ISSUE TITLE
the macro received maybe wrong 

### ISSUE THREAD

**Issue by zztczcx** [elixir-lang/elixir-lang.github.com#436]
Our macro_unless macro received the following:
macro_unless(true, {{:., [], [IO, :puts], [], ["this should never be printed"]}})

when I learned this http://elixir-lang.org/getting_started/meta/2.html#2.2-macros-hygiene chapter,
I have a little confused about the macro received

so I try it in the iex and I get something like this form
{{:., [line: 2], [{:__aliases__, [counter: 0, line: 2], [:IO]}, :puts]}, [line: 2], ["this should never be printed"]}

this is conformed to the quoted format

**Comment by ericmj** [comment]
I am unable to reproduce, can you provide reproducing code?

**Comment by zztczcx** [comment]
I just add a line IO.puts(inspect(expression)) to the module 
defmacro macro_unless(clause, expression) do
     IO.puts(inspect(expression))
     quote do
        if(!unquote(clause), do: unquote(expression))
      end
 end

then in the iex 
iex> require Unless
iex> Unless.macro_unless true, IO.puts "this should never be printed"

and it print {{:., [line: 2], [{:aliases, [counter: 0, line: 2], [:IO]}, :puts]}, [line: 2], ["this should never be printed"]}

this is a tuple with three elements

**Comment by josevalim** [comment]
Exactly! A pull request that updates the current code would be very welcome! :D
