### ISSUE TITLE
Getting Started Guide: rename files by "name"

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#442]
There is one crucial issue with the Getting Started Guide: File names use numbers, not names. This will cause the site to eventually break when pages are removed, or new pages are added, as it's currently happening, and [planned](#405).

In order to to this we need to device a way to store the page order for each section of the guide. I've been looking at a few solutions, but first I need to hear opinions.

**Comment by whatyouhide** [comment]
:+1: all the way! Problem is we don't want to break all existing links to the current chapters either, but I can't think of a way to "redirect" using Jekyll.

**Comment by eksperimental** [comment]
there is a plugin for that

**Comment by eksperimental** [comment]
https://github.com/jekyll/jekyll-redirect-from

Just add this code to the top of the page (YAML frontmatter)
```
redirect_from:
  - /getting_started/mix_otp/2.html
```

**Comment by whatyouhide** [comment]
@eksperimental Yeah I had a look at that and at https://github.com/nquinlan/jekyll-pageless-redirects as soon as you commented :). Nice stuff, would definitely help with this issue.

**Comment by eksperimental** [comment]
@whatyouhide your option is even better for this job

**Comment by josevalim** [comment]
Yeah, great point! let's migrate from numbers!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by whatyouhide** [comment]
@eksperimental is right though, we have to think of a way to store the order of the chapters in the guides.

**Comment by eksperimental** [comment]
i found two possible solutions: non of them tested,
http://stackoverflow.com/a/16625534/1660683
http://stackoverflow.com/a/25513956/1660683

and we already have the value
`guide: `
which is the order (same number as the file name)

**Comment by eksperimental** [comment]
i think the examples above don't suit our needs,
i have create the structure:
https://gist.github.com/eksperimental/4d7b1c392f6d401bd4c5

and it should be saved in: `_data/getting_started.yml`

I will see if I can come up with something good

**Comment by josevalim** [comment]
The index in the sidebar is the order, no?



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by eksperimental** [comment]
you talking about this file?
https://gist.githubusercontent.com/eksperimental/4d7b1c392f6d401bd4c5/raw/c987ee755460c6c546d721c89c64ddc0bd5a4e93/getting_started

**Comment by eksperimental** [comment]
done. i will post it soon

**Comment by eksperimental** [comment]
[https://github.com/elixir-lang/elixir-lang.github.com/pull/443#issuecomment-72953120](After a  discussion) with @whatyouhide, it seems obvious to me that for the exact same reasons, we should not use numbers in internal links.

If I want to link to **"Sigils >> Strings"**, that link nowadays is:
**http://elixir-lang.org/getting_started/18.html#18.2.1-strings**
whereas it should be
**http://elixir-lang.org/getting_started/sigils.html#strings**

**Comment by eksperimental** [comment]
anothing thing I noticed, is that the only two files/folder that use underscore, instead of hyphen, for the whole site, are: 
* getting_started
* getting_started/mix_otp

maybe is the right time to rename those, to have consistency across the site.

**Comment by josevalim** [comment]
:heart_eyes:
