### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#444]
I'm fixing everything that has to do with redirection and dead links in the web site. While I was able to fix pretty much all of them, there are a few that I will need your help @josevalim or anybody else who's familiar with the site.

* [this post](http://elixir-lang.org/blog/2012/08/01/elixir-v0-6-0-released/) links to http://elixir-lang.org/blog/2012/07/05/what-s-new-in-elixir-5/
I know all these posts were moved, in one go. So, where should we link. or shall we remove that paragraph?

* [same post](http://elixir-lang.org/blog/2012/08/01/elixir-v0-6-0-released/) links to http://elixir-lang.org/getting_started/ex_unit/1.html
I see this guide has been posted to other sites like read the docs, but.. what happened to it. I cannot find the chapter that it was merged in the Getting Started Guide (if it ever was merged).

* [Docs: Elixir Version]/docs/stable/elixir/Version.html links to http://elixir-lang.org/docs/stable/elixir/Version.Requirement.html#t:t/0
This [is a reported issue](https://github.com/elixir-lang/ex_doc/issues/110) some time ago. Just worth mentioning. So far the only broken link the the docs.

other than that, the rest has been fixed

**Comment by josevalim** [comment]
1. lets remove the paragraph

2. let's remove the "Of course the documentation..." sentence

3. i have just made Version.Requirement public

**Comment by eksperimental** [comment]
@josevalim done, all commited in #443
