### ISSUE TITLE
Link to "Meta Programming in Elixir"

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#447]
I have checked the links, and this guide is getting very little attention, 
the only place where it is actually being linked to is this post:
http://elixir-lang.org/blog/2014/04/21/elixir-v0-13-0-released/

and that's it.
I think we should at least include it at the end of the Getting Started guide
http://elixir-lang.org/getting-started/where-to-go-next.html#21.1-build-your-first-elixir-project
Aftet the Mix & OTP guide is mentioned.

**Comment by josevalim** [comment]
Sounds great.

**Comment by eksperimental** [comment]
If someone wants to tackle, please do so.

**Comment by whatyouhide** [comment]
I added the link to the "What's next chapter", I'm waiting for #448 to be merged so that I can open a PR with the header numbers already removed :).
