### ISSUE TITLE
Reformulate "Contributing improvements or bug fixes"

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#451]
We should revamp this sections: https://github.com/elixir-lang/elixir-lang.github.com/blob/master/README.md#contributing-improvements-or-bug-fixes

Earlier today when I was testing a few changes that were working locally and not remotely, I ended up finding this article:
https://help.github.com/articles/using-jekyll-with-pages/

especially:
https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll
https://help.github.com/articles/using-jekyll-with-pages/#running-jekyll

which is telling us to install `gem github-pages`, with `bundle`
and run jekyll using `bundle exec jekyll serve`

that way we ensure what we run locally is the same as what's running in the github servers.

**Comment by eksperimental** [comment]
also if we are ok with using bundle, i will push `Gemfile` which is required

**Comment by whatyouhide** [comment]
:+1: on pushing the Gemfile!

On Friday, February 6, 2015, eksperimental <notifications@github.com> wrote:

> also if we are ok with using bundle, i will push Gemfile which is required
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/451#issuecomment-73259383>
> .
>


-- 

Andrea Leopardi
an.leopardi@gmail.com

**Comment by josevalim** [comment]
:+1:

**Comment by whatyouhide** [comment]
I think this can be closed after #465 has been merged :smiley:

**Comment by eksperimental** [comment]
good job!
