### ISSUE TITLE
Install: suggest permanent solution for updating PATH env. variable

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#461]
From: http://elixir-lang.org/install.html

> After compiling, you are ready to run the elixir and iex commands from the bin directory. It is recommended that you add Elixir's bin path to your PATH environment variable to ease development:
> `$ export PATH="$PATH:/path/to/elixir/bin"`

This is a temporary solution that will last as long as the terminal window is open. 
The thing is that the solution is a bit more complicated because it depends on the shell you are using.
as listed here: http://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables/117470#117470
Bash has four different profile files, and some are used in some distroes and some in others.

i'm thinking of saying something like

> After compiling, you are ready to run the elixir and `iex` commands from the bin directory. It is recommended that you add Elixir's bin path to your PATH environment variable to ease development. You need to [find your shell profile file](http://unix.stackexchange.com/a/117470/101951), and add to the end of it: 
> `$ export PATH="$PATH:/path/to/elixir/bin"`

**Comment by josevalim** [comment]
:+1:
