### ISSUE TITLE
Add Elixir Cookbook to learing resource list

### ISSUE THREAD

**Issue by Linicks** [elixir-lang/elixir-lang.github.com#474]
I noticed a new Elixir book that isn't on the current learning resource book list, and thought you may want to add it:

Elixir Cookbook - https://www.packtpub.com/application-development/elixir-cookbook#

**Comment by josevalim** [comment]
Yes, @pma contacted me already. :) I need to redesign the learning section
and it is actually scheduled to be done tomorrow.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by eksperimental** [comment]
too bad that all the code sample in that book uses: `elixir: "~> 0.15.1",` considering that it was put out, months after elixir 1.0 has been released.

**Comment by josevalim** [comment]
The new learning page is there. New resources are welcome, they must have been officially published and work on latest Elixir (i.e. v1.0 right now).

**Comment by eksperimental** [comment]
jose, just out of curiosity, what happened to "Introducing Elixir" ?
