### ISSUE TITLE
Bring back numbers to TOC

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#479]
I was looking at Wikipedia, http://en.wikipedia.org/wiki/Elixir
and they only use numbers in the TOC, and not in the heading, like we were having before.
I don' t mind the numbers in the headings (only for the getting started guide),
But I think we were better off with the numbers in the table of contents, that without them.

**Comment by josevalim** [comment]
Definitely, agreed.
