### ISSUE TITLE
Gemfile.lock : Add to .gitignore?

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#484]
Should we remove Gemfile.lock and add it to .gitignore and let the developers create it themselves.
Some people says it's good,
http://stackoverflow.com/a/4151540/1660683

some other people say it is not, because it may to be portable the file.

One benefit now that we are gonna build on travis is that it speeds up the buildin process,
but I'm inclined to remove it.
opinions?

**Comment by josevalim** [comment]
No, I am on the camp it is a bad idea because people should be able to reproduce the build that works. :)

**Comment by eksperimental** [comment]
I don't know the internals of this file.
so what happens when someone who uses windows, runs it the file gets modified? and submits a commit
