### ISSUE TITLE
Note on erlang-base installation

### ISSUE THREAD

**Issue by shankardevy** [elixir-lang/elixir-lang.github.com#487]
It would be good to add a note about the nature of erlang installation when someone install elixir as outlined in http://elixir-lang.org/install.html

```
sudo apt-get install elixir
```

The above command installs only `erlang-base` which doesn't include many of the erlang modules. For eg, it doesn't install some of the required modules for installing Phoenix such as `erlang-ssl`, `erlang-inets`. 

People who install elixir will also be interested in  phoenix and other elixir projects. The lack of information regarding missing erlang modules could potentially slow down people from exploring elixir. One another example is this project https://github.com/elpulgardelpanda/sshex needs erlang module :ssh which is not available in elixir installation by default following the installation guide above.

Below command installs all of erlang modules and solves the issues mentioned.

```
sudo apt-get install erlang
```

**Comment by eksperimental** [comment]
well, if that's the case I think it's something to add to the phoenix installation instructions

**Comment by eksperimental** [comment]
I think it should be consistent with the other linux installation, if only erlang-base is installed in the other ones, i think we should not make it different for ubuntu. if the other ones are installing full erlang, then we should include it.

**Comment by shankardevy** [comment]
@eksperimental I installed elixir on mac using brew and I never had the issue of missing erlang modules.  So basically brew installed a full erlang system. It was only yesterday I started using elixir on an ubuntu machine and faced all sorts of problem and hence the request.

**Comment by ericmj** [comment]
Mix, which I assume is bundled in the Elixir package on Ubuntu requires ssl and inets. So we should ask the maintainers to fix the dependencies for the Elixir package. I still think it would be useful to mention the differences between erlang and erlang-base packages because many seems to have issues with it.

**Comment by josevalim** [comment]
Pushed to master.
