### ISSUE TITLE
is_regex doesn't exist

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#488]
it's mentioned in crash-course.markdown

```elixir
is_regex ~r"""
This is a regex
spanning several
lines.
"""
```
`is_regex` doesn't exist, and what is the function to determine if a regular expression is such?

we can fix the example like that in any case.
```elixir
multine_regex = ~r"""
This is a regex
spanning several
lines.
"""
```

**Comment by josevalim** [comment]
Yup, let's remove it. Just match on `%Regex{}` instead.

**Comment by eksperimental** [comment]
so are you alright with the "multine_regex"  ?

**Comment by eksperimental** [comment]
actually, i just realized we have `Regex.regex?`
