### ISSUE TITLE
Add is_* functions to "Expressions in guard clauses"

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#499]
in http://elixir-lang.org/getting-started/case-cond-and-if.html#expressions-in-guard-clauses
ther are a handful of "is_*" functions that are missing,
but they are not all of them are "type check functions"

* is_even/1
* is_nil/1
* is_odd/1
* Record.is_record/1
* Record.is_record/2

neither is "is_number/1" which is currently listed as a type check function.

How should we put this together?

**Comment by josevalim** [comment]
We should add `is_nil`. I wouldn't add the ones in Integer and Record but maybe we could mention that modules may define their own guards and they start with `is_`.

**Comment by eksperimental** [comment]
so should we remove is_number from the current list?

**Comment by josevalim** [comment]
No because `is_number` is in Kernel.
