### ISSUE TITLE
Remove all redirect_from from the project

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir-lang.github.com#556]
@eksperimental I think we are ready. All search engines probably updated their indexes. :) What do you think?

**Comment by eksperimental** [comment]
I'm :-1:  on this one, as there are many websites still linking to the old urls
https://www.google.com/search?q=%22elixir-lang.org%2Fgetting_started%2F*%22&oq=%22elixir-lang.org%2Fgetting_started%2F*%22&ie=UTF-8

even out own stable documentation is linking to them.
http://elixir-lang.org/docs/v1.0/elixir/GenEvent.html

**Comment by josevalim** [comment]
Perfect. Thank you!
