### ISSUE TITLE
Security! - always provide link to packages through https

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#566]
In the same fashion of https://github.com/elixir-lang/elixir-lang.github.com/pull/563 , 
I think all links provided in our website to any installable, should be offered through a secure connection.

**[erlang.csv](https://github.com/elixir-lang/elixir-lang.github.com/blob/a09a7f9a28057308211acd7f1883eaea9826a433/erlang.csv)**
Should't we use https links,
Erlang solutions provides the same files, just with different names, 
https://www.erlang-solutions.com/downloads/download-erlang-otp 
should we replace them?

**[install.markdown](https://github.com/elixir-lang/elixir-lang.github.com/blob/a09a7f9a28057308211acd7f1883eaea9826a433/install.markdown)**
**[_posts/2014-08-07-elixir-v0-15-0-released.markdown](https://github.com/elixir-lang/elixir-lang.github.com/blob/a09a7f9a28057308211acd7f1883eaea9826a433/_posts/2014-08-07-elixir-v0-15-0-released.markdown)**
> * [Download the installer](http://s3.hex.pm/elixir-websetup.exe)

I think we should upload this to a secure server

**[install.markdown](https://github.com/elixir-lang/elixir-lang.github.com/blob/a09a7f9a28057308211acd7f1883eaea9826a433/install.markdown)**
> The only prerequisite for Elixir is Erlang, version 17.0 or later, which can be easily installed with [Precompiled packages](https://www.erlang-solutions.com/downloads/download-erlang-otp). In case you want to install it directly from source, it can be found on [the Erlang website](http://www.erlang.org/download.html) or by following the excellent tutorial available in the [Riak documentation](https://docs.basho.com/riak/latest/ops/building/installing/erlang/).

erlang-solutions provide over https:// the source files, the only thing is that it is not possible to link directly to the souce tab.

**[_includes/elixir-radar.html](https://github.com/elixir-lang/elixir-lang.github.com/blob/a09a7f9a28057308211acd7f1883eaea9826a433/_includes/elixir-radar.html)**
Not a must, but I feel the need to mention it. I think it will be good if the Elixir radar link could use https, since people will be providing their email address:
http://plataformatec.com.br/elixir-radar?utm_campaign=elixir_lang_cta&utm_medium=cta&utm_source=elixir_lang_website

**[Elixir Website](http://elixir-lang.org)**
and above all, the most important thing to secure if we want to offer secure links is our own project's website,
so I think it will be ideal if we could serve http://elixir-lang.org through https
There is one option (for free) to serve pages securely hosted in github
https://me.net.nz/blog/github-pages-secure-with-cloudflare/
but I haven't tested it myself.

What do you guys think?

**Comment by ericmj** [comment]
:+1:

http://s3.hex.pm/... links can be changed to https://s3.amazonaws.com/s3.hex.pm/...

**Comment by ericmj** [comment]
The problem with using Cloudflare's free SSL option is that it doesn't work on older browsers. Going for the paid option or moving from github hosting might be worth it if we want https for elixir-lang.org

**Comment by josevalim** [comment]
Yes, let's migrate at least the installers to https .

**Comment by eksperimental** [comment]
@ericmj oops. i forgot to mention that in my comment (that's what I got from the article)

@josevalim is it ok to replace the files in erlang.csv ? actually what is that file used for.

Does anybody know how to contact the peopler of erlang-solutions.com . their contact form in their website is missing and i couldn't find an email address.
I would like to tell them about their missing contact form and also if they could do something so we can link directly from our website to download source files.

**Comment by ericmj** [comment]
erlang.csv is used for the windows installer. We can move it to S3 if necessary, but do we even know if the installer even uses https?

**Comment by josevalim** [comment]
@ericmj we would need to try to be sure, i don't think we can change the erlang.csv location without rebuilding the installer. But this is a good time because our code signing license is expiring anyway.

@chyndman, do we support https in the installer?

**Comment by chyndman** [comment]
@josevalim Yes; the [download plugin](https://mitrichsoftware.wordpress.com/inno-setup-tools/inno-download-plugin/) claims support for HTTPS.  Let me know the URL's to use and I can whip up a test build.

**Comment by josevalim** [comment]
@eksperimental can you give us the https URLs for the erlang packages please?

@chyndman @eksperimental :heart:

**Comment by eksperimental** [comment]
@josevalim @chyndman I don't have them listed, you will have to visit: https://www.erlang-solutions.com/downloads/download-erlang-otp and WINDOWs tab, and extract them from there.
sorry, i 'm going offline now, otherwise I will you the links..

**Comment by eksperimental** [comment]
you will get http links, but if you prefix them with https they should work.
https://packages.erlang-solutions.com/erlang/
just to be sure, check with erlang-solutions that they arenot planning on moving the location of the files (just based on the way the url looks https://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_3_general/esl-erlang_18.0-1~windows_i386.exe)

**Comment by eksperimental** [comment]
@chyndman @eksperimental @ericmj 
Another way to solve the problem with the plain connection issue loading from http://elixir-lang.org instead of moving it to S3, is to use the link to the raw file in github

is to instead of linking/downloading:
http://elixir-lang.org/elixir.csv
http://elixir-lang.org/erlang.csv

it to use:
https://github.com/elixir-lang/elixir-lang.github.com/raw/master/elixir.csv
https://github.com/elixir-lang/elixir-lang.github.com/raw/master/erlang.csv

Note that both links are redirects. so the downloader needs to deal with that. But those are the links provided by github in the repo, so I think it's better to stick to these one.
