### ISSUE TITLE
Updates to Mix and OTP Tutorial

### ISSUE THREAD

**Issue by benhamill** [elixir-lang/elixir-lang.github.com#573]
I've got Elixir 1.0.3 on my system and am working through the tutorials. Here's some stuff I found. Let me know if you want me to break them up into separate Issues, or if I should just fork and make this a PR with the fixes.

* In [the Introduction to Mix section about Project Compilation](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#project-compilation), the example of mix.exs is missing the `elixir: "~> 1.0",` line from the `project`definition.
* In [the GenEvent section about Event Streams](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#project-compilation), the example code shows `spawn_link` returning `:ok`, but it looks like it should be returning something like `#PID<0.98.0>`.
* In [the Supervisor and Application section about Starting Applications](http://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html#starting-applications), the example using `iex -S mix run --no-start` indicates that running `Application.start(:kv)` should return `{:error, {:not_started, :logger}}`. On my machine, it return `:ok` (I guess the logger got started automatically?).
* In [the ETS section about ETS As Persistent Storage](http://elixir-lang.org/getting-started/mix-otp/ets.html#ets-as-persistent-storage), the testing output differs slightly from mine [as outlined in this gist](https://gist.github.com/benhamill/1127bc06b5ab02c3644a).
* In [the Distributed Tasks and Configuration section about Our First Distributed Code](http://elixir-lang.org/getting-started/mix-otp/distributed-tasks-and-configuration.html#our-first-distributed-code), the tutorial says, "We will use jv@computer-name in the following...", but actually uses `foo@computer-name`.

**Comment by benhamill** [comment]
Let me know if I should just PR these changes.

**Comment by josevalim** [comment]
Please send a PR for 1, 3, and 5. I need to further investigate 2 and 4 but at first it seems something else is wrong. :)

**Comment by ericmj** [comment]
You can send a PR for 4 also. The error message was just improved to include the timeout and mailbox.

**Comment by sircharleswatson** [comment]
@benhamill @josevalim 

Along the lines of number 2 in that list (the GenEvent section):

I was following along just fine and then the tutorial says
> Open up lib/kv/registry.ex and paste the new registry implementation below (comments inlined):

So I did that but then my tests are still failing. it seems as though I'm not getting responses back correctly

The error is:
```
1) test send events on create and crash (KV.RegistryTest)
     test/kv/registry_test.exs:38
     No message matching {:exit, "shopping", ^bucket} after 100ms.
     The following variables were pinned:
       bucket = #PID<0.111.0>
     Process mailbox:
       {:gen_event_EXIT, KV.RegistryTest.Forwarder, {:bad_return_value, {:create, "shopping", #PID<0.111.0>}}}
     stacktrace:
       test/kv/registry_test.exs:44
```

I'm also getting messages that say:
```
12:47:26.108 [error] GenEvent handler KV.RegistryTest.Forwarder installed in #PID<0.109.0> terminating
** (stop) bad return value: {:create, "shopping", #PID<0.111.0>}
Last message: {:create, "shopping", #PID<0.111.0>}
State: #PID<0.107.0>
```

I'm not sure exactly what's going on since I'm new to Elixir but I'm guessing those shouldn't be happening :stuck_out_tongue: 

Here is what my test looks like and what the guide shows us to put in:
```
test "sends events on create and crash", %{registry: registry} do
  KV.Registry.create(registry, "shopping")
  {:ok, bucket} = KV.Registry.lookup(registry, "shopping")
  assert_receive {:create, "shopping", ^bucket}

  Agent.stop(bucket)
  assert_receive {:exit, "shopping", ^bucket}
end
```
