### ISSUE TITLE
Giving priority to sidebar rather than content?

### ISSUE THREAD

**Issue by anandubajith** [elixir-lang/elixir-lang.github.com#586]
In the getting started pages, the html is structured in such way that the sidebar loads first .
shouldn't it be restructured so that content gets more priority that sidebar?

**Comment by josevalim** [comment]
I think the current mechanism is just fine, as the sidebar, specially in the getting started, is used for navigation and not for extra contents.

**Comment by eksperimental** [comment]
But i also notice some inconsistencies with the rest of the site. Like the elixir radar and other stuff in the sidebar that appear at the bottom in the rest of the site.. Appear on top here

**Comment by eksperimental** [comment]
I think we should consider doing something about this.
it's son long and it's at the top of the page, that it becomes impractical.
maybe we should display the contents as a drop-down list (only for mobile devices ofcourse)
