### ISSUE TITLE
move Windows building instructions from wiki to website

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#588]
reading http://elixir-lang.org/install.html#compiling-from-source-unix-and-mingw
I would like to bring this page
https://github.com/elixir-lang/elixir/wiki/Windows
into the website,
it hasn't been updated and it's a bit weird to take the user out of the website, fro something like this,
also that page has never been updated in one year since it was created, I think it will receive more attention being home.
what you guys think

**Comment by josevalim** [comment]
I would like to leave it as is so folks can contribute improvements in case necessary in the future. We have very little experience with building on Windows and I would like to leave contributing new instructions straight-forward.
