### ISSUE TITLE
Maps in Getting-Started: update vs create

### ISSUE THREAD

**Issue by da99** [elixir-lang/elixir-lang.github.com#604]
Am I reading the following incorrectly? It's from: [master/getting-started/maps-and-dicts.markdown](https://github.com/elixir-lang/elixir-lang.github.com/blob/master/getting-started/maps-and-dicts.markdown)
```
   One interesting property about maps is that they provide
   a particular syntax for updating and accessing atom keys:
   ...
   iex> %{map | :a => 2}
```
That seems to be a `create`, not `update`.
I'm using Elixir 1.0.5 from git master. 
Would this be a better re-write?: `  iex> map = %{map | :a => 2} `

**Comment by eksperimental** [comment]
it is correct, you cannot create new elements in the map with that sintax

```elixir
iex(12)> map = %{foo: nil}  
%{foo: nil}
iex(13)> %{map | foo: :bar}
%{foo: :bar}
iex(14)> %{map | zoo: :nope}
** (KeyError) key :zoo not found in: %{foo: nil}
    (stdlib) :maps.update(:zoo, :nope, %{foo: nil})
    (stdlib) erl_eval.erl:255: anonymous fn/2 in :erl_eval.expr/5
    (stdlib) lists.erl:1262: :lists.foldl/3
```

what your proposal does is reassign a new maps to `map`

**Comment by da99** [comment]
Thanks. That cleared it for me.

**Comment by eksperimental** [comment]
cool.
please note that the error in the guide is wrong,
it is not "Argument error". it should be what i posted in me previous comment. (KeyError)
i have just submitted a PR.
https://github.com/elixir-lang/elixir-lang.github.com/pull/605

thanks to this Issue, it made me spot the mistake,
