### ISSUE TITLE
Pattern vs. value

### ISSUE THREAD

**Issue by dmitrytrager** [elixir-lang/elixir-lang.github.com#614]
I'm sorry if I miss something, but on [this page](http://elixir-lang.org/getting-started/mix-otp/genevent.html) I found
![this test](https://monosnap.com/file/tGnfH0S3aE9inM0iheA9XxtMf2bJai.png)

Below is says:
>  Also note that assert_receive expects a pattern, rather than a value, that’s why we have used ^bucket, with the pin operator, to match on the bucket pid.

So doesn't this mean that assertion expects a value?

**Comment by josevalim** [comment]
`^bucket` is a pattern that asks you to match on a value. If you passed only `bucket` , it would match anything.

**Comment by dmitrytrager** [comment]
So it's not clear how could assert expect for value in this case)
but ok, thanks, now it's much clear for me

**Comment by josevalim** [comment]
`assert_received ^value` if you want to match on any value in a variable.
