### ISSUE TITLE
Elixir 1.1 setup windows 7, elixir shortcut target property incorrect

### ISSUE THREAD

**Issue by qt3m45su0najc7** [elixir-lang/elixir-lang.github.com#617]
Downloaded and installed version as of 10/10/2015 (elixir v 1.1), ran elixir-websetup (filesize 1583336 bytes). Elixir seemed setup correctly (tested by running iex.bat in program files (x86).  The problem was in the creation of the Elixir shortcut, which __*incorrectly*__ pointed to an executable on my desktop, but I revised it to the following:

    "C:\Program Files\erl7.0\bin\werl.exe" -env ERL_LIBS "C:\Program Files (x86)\Elixir\lib" -user Elixir.IEx.CLI -extra --no-halt

Please confirm and update if needed.

**Comment by josevalim** [comment]
Thank you @qt3m45su0najc7! Do you remember what was the value before your changes?

**Comment by qt3m45su0najc7** [comment]
I do not recall exactly, but something like __c:\users\{mylocalaccountname}\desktop__ followed by all the parameters
