### ISSUE TITLE
Updated section for Behaviour

### ISSUE THREAD

**Issue by brentonannan** [elixir-lang/elixir-lang.github.com#620]
[`Behaviour`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/behaviour.ex#L3) has been deprecated, but the getting started guide section on [defining behaviours](https://github.com/elixir-lang/elixir-lang.github.com/blob/master/getting-started/typespecs-and-behaviours.markdown#defining-behaviours) still uses `defcallback`.

**Comment by josevalim** [comment]
We would appreciate a PR that changes it to use `@callback`. If not, we will get to it later. :) Thank you!

**Comment by brentonannan** [comment]
I'd love to, just trying to figure out how to do it myself, which is what led me to it ;D

If I get it straight myself I'll PR for sure. Cheers for the quick reply.
