### ISSUE TITLE
Change HashDict references to Map in Mix / OTP guide

### ISSUE THREAD

**Issue by riverrun** [elixir-lang/elixir-lang.github.com#623]
The Mix / OTP guide uses HashDicts in the examples.

Do we want to change these to use Maps instead -- as Maps seem to be the favored Dict implementation?

I'd be happy to do this myself. Just let me know, and I can send you  a pull request.

**Comment by ericmj** [comment]
Maps will be favored over HashDicts when Elixir 1.2 is out. For now we have to write the guides against the lowest common denominator which is OTP 17 where large maps are slow.

**Comment by riverrun** [comment]
Ok.
