### ISSUE TITLE
Clarify performance of Maps in mix_otp

### ISSUE THREAD

**Issue by diogovk** [elixir-lang/elixir-lang.github.com#633]
In http://elixir-lang.org/getting-started/mix-otp/agent.html:
"Note that we are using a HashDict to store our state instead of a Map, because in the current version of Elixir maps are less efficient when holding a large number of keys"

Tecnically that's correct assuming you're using Erlang17, but with Erlang18 that's not the case anymore, is it? 
( https://gist.github.com/BinaryMuse/bb9f2cbf692e6cfa4841 )

Should we clarify that HashDict are faster only when using Erlang version <= 17?

**Comment by josevalim** [comment]
Thank you! Right now, the recommendation is still to use HashDict until Elixir v1.2 is out because Elixir v1.1 code is meant to be compatible with all Erlang versions. We will amend this when 1.2 is finally released. :)
