### ISSUE TITLE
Closed socket handling in server from 'Docs, tests & pipelines'

### ISSUE THREAD

**Issue by petert82** [elixir-lang/elixir-lang.github.com#638]
I've been following the (brilliant!) 'Mix and OTP' tutorial from the Getting Started guide, and I've just got to the end of the '[Docs, tests & pipelines](http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-pipelines.html) page.

Playing around with the server that's been implemented at this stage of the tutorial via telnet, I noticed that if I disconnected my telnet client, my laptop's CPU usage skyrocketed. After dropping a few calls to IO.puts into my server code, I realised that after the data socket is closed, the server continues trying to read from it, receiving "{:error, :enotconn}" each time and continuing like this forever.

I'm wondering now if I missed something in the tutorial - though I'm reasonably confident I copied all the code correctly - or if this is just a scenario that's deliberately overlooked for brevity. In the latter case, maybe it should be mentioned that 'real' code should deal with the case of the socket being closed?

**Comment by josevalim** [comment]
Fixed in a branch, thank you!
