### ISSUE TITLE
GenServer guide introduce a race condition without notice

### ISSUE THREAD

**Issue by sanrodari** [elixir-lang/elixir-lang.github.com#643]
Having in consider the create callback for the GenServer example:

```elixir
def handle_cast({:create, name}, names) do
  if HashDict.has_key?(names, name) do
    {:noreply, names}
  else
    {:ok, bucket} = KV.Bucket.start_link()
    {:noreply, HashDict.put(names, name, bucket)}
  end
end
```

In the [Testing a GenServer][testing] section a new bucket is created via a cast callback (asynchronously):

```elixir
KV.Registry.create(registry, "shopping")
assert {:ok, bucket} = KV.Registry.lookup(registry, "shopping")
```

So, when the assert is executed there is no guarantee that the bucket has been created because .create triggers an asynchronous update in the server.

It should be a notice/warning saying to the reader that a race condition is introduced in the guide.

[testing]: https://github.com/elixir-lang/elixir-lang.github.com/blob/master/getting-started/mix-otp/genserver.markdown#testing-a-genserver

**Comment by ericmj** [comment]
create is asynchronous but a GenServer can only do one thing at a time so the lookup will only run after create has finished.

**Comment by josevalim** [comment]
@sanrodari is correct. :) all operations are serialized against the gen server, so we are fine!

**Comment by sanrodari** [comment]
Sorry about the false positive. Thanks guys for the explanation, now I understand why it does not introduce a race condition.
