### ISSUE TITLE
Link to "Docs, tests and with" breaks under getting started

### ISSUE THREAD

**Issue by sandeshsoni** [elixir-lang/elixir-lang.github.com#650]
In **Getting Started**,
under tab *MIX AND OTP*,
url *Docs, tests and with* redirects to 404 page.
*serial no 8 in nav bar*
link address http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html

**Comment by sandeshsoni** [comment]
I am working on this issue

**Comment by sandeshsoni** [comment]
Fixed and opened a pull request

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
