### ISSUE TITLE
Question about typo on 'Getting Started'.

### ISSUE THREAD

**Issue by riseshia** [elixir-lang/elixir-lang.github.com#657]
I have one small question in the section '`do/end` blocks' on [case cond and if](https://github.com/elixir-lang/elixir-lang.github.com/blob/master/getting-started/case-cond-and-if.markdown).

There is text, 'Notice how the second example has a comma between `true` and `do:`', I think 'true' should be 'false'. how do you think? Actually, I'm not english native, I can't convince this. that's why i don't send PR. ;)

Anyway, if correct, please fix this or let me send fix.
Thanks to read, Thanks to guide :)

**Comment by josevalim** [comment]
I have fixed it to say "the example above" and not "second example" to get rid of the confusion. Thank you! :)
