### ISSUE TITLE
Getting Started references nonexistent IEx function 'i'

### ISSUE THREAD

**Issue by kaizerroll** [elixir-lang/elixir-lang.github.com#667]
In [Getting Started - Basic Types - Linked List](http://elixir-lang.org/getting-started/basic-types.html#linked-lists) there is a reference to a helper function `i` that can be invoked in IEx to retrieve information about a value.

`i` doesn't appear to currently be a helper function in IEx.  

```
iex:4: undefined function i/0
```

If this section could be updated with whatever the current replacement for `i` is (if there is any) that would be greatly appreciated.

Version info:
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.1.1

**Comment by kaizerroll** [comment]
I realize now this is a 1.2 feature. Closing this.

**Comment by josevalim** [comment]
Yes, you should update :D
