### ISSUE TITLE
Suggest to change 'and' to '\x26'on "Getting Started#sigils"

### ISSUE THREAD

**Issue by riseshia** [elixir-lang/elixir-lang.github.com#669]
Hi. I have one suggestion about one example.

Here is example in [guide](http://elixir-lang.org/getting-started/sigils.html)
```iex
iex> ~s(String with escape codes \x26 #{"inter" <> "polation"})
"String with escape codes & interpolation"
iex> ~S(String without escape codes and without #{interpolation})
"String without escape codes and without \#{interpolation}"
```

This example give comparison between '~s' and '~S', meaning to say,
it may show interpolation and escape work or not clearly on both example.
And to me, this example intend to show how escape work with '\x26',
how interpolation work with '#{"inter" <> "polation"}'.
However, 'and' instead of '\x26' on the second example code, so only reader could see
is  '\#' instead of '#'.

Hence, my suggestion is this,
how about change 'and' to '\x26' like,

```iex
iex> ~s(String with escape codes \x26 #{"inter" <> "polation"})
"String with escape codes & interpolation"
iex> ~S(String without escape codes \x26 without #{interpolation})
"String without escape codes \\x26 without \#{interpolation}"
```

or If this is not intended, inverse is also enable. :)

Thanks in advance.

**Comment by josevalim** [comment]
Yes! Could you please send a pull request :)
