### ISSUE TITLE
Typo in INSTALL section

### ISSUE THREAD

**Issue by Ivo-Balbaert** [elixir-lang/elixir-lang.github.com#678]
In §6. Setting PATH environment variable

It is stated that one should add the following to one's shell profile file: 

export PATH="$PATH:/path/to/elixir/bin"

The typo is:  the double quotes are not necessary, and it is even an error when one changes the PATH with the ""

It should be without "" like:

export PATH=$PATH:/path/to/elixir/bin

Best regards,
Ivo

**Comment by whatyouhide** [comment]
The Advanced Bash Scripting Guide contains [a chapter on quoting variables](http://tldp.org/LDP/abs/html/quotingvar.html) and it says:

> When referencing a variable, it is generally advisable to enclose its name in double quotes.

I think the problem with `$PATH` would be if filenames in `PATH` contain spaces. Here's [another related unix.stackexchange question](http://unix.stackexchange.com/questions/78002/when-to-use-double-quotes-with-a-variable-in-shell-script) that suggests to do the same.

**Comment by josevalim** [comment]
Yup. It is more likely you will have a path with spaces than one with double quotes. :)

**Comment by eksperimental** [comment]
wouldn't this be the best of both worlds?
`export PATH="${PATH}":/path/to/elixir/bin`

**Comment by josevalim** [comment]
It wouldn't solve the first problem which is another PATH in PATH having ".

**Comment by eksperimental** [comment]
It seems to work just fine (bash and dash)

```sh
$ XPATH="/space and \"quotes\""
$ export XPATH="${XPATH}":/path/to/elixir
$ echo ${XPATH}
/space and "quotes":/path/to/elixir
$ export XPATH="${XPATH}":/path/to/elixir
$ echo ${XPATH}
/space and "quotes":/path/to/elixir:/path/to/elixir
```
