### ISSUE TITLE
Talk about running in production in the Mix and OTP guide

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir-lang.github.com#680]
We need to at least mention the production environment, talk about explicit compilation, _build and deps directory and both Elixir and Erlang requirement. Also mention exrm.

**Comment by pjhampton** [comment]
I could give this a go if no one is already on it? I have quite a few outward PRs at the moment, but I reckon a turnaround time of about ~7 days is feasible.

**Comment by josevalim** [comment]
@pjhampton that would be great, thank you!

**Comment by pjhampton** [comment]
Quick update @josevalim 

I'm only half way through the updated Mix / OTP guides. I want to finish them before I contribute anything so it seems seamless. I thought that would be best since they have changed a little since last going though them a year or so ago. Sorry for this delay - Hopefully a PR soon!

**Comment by josevalim** [comment]
No worries @pjhampton! Take your time!

**Comment by bobbypriambodo** [comment]
\*Friendly bump\* 🙂

I just noticed that there are no mention of any kind of production deployment in elixir-lang.org. How is this issue progressing?

**Comment by josevalim** [comment]
We have plans to do so but not quite yet. Distillery has reached 1.0, so we may be able to get started soon.

The other point is that each application may require slightly different setups. For example, deploying a Nerves app is quite different from a Phoenix one, and this guide would still be different than both of them. At least the current app would likely be a subset, which is a good thing.

**Comment by pjhampton** [comment]
Opps, sorry guys. If you don't mind I will release this back into the wild (for now). I'm pretty busy with work and other open source projects.
