### ISSUE TITLE
Provide a git repository for the mix-otp tutorial

### ISSUE THREAD

**Issue by davidspiess** [elixir-lang/elixir-lang.github.com#682]
At the moment i'm working through the (great) tutorial and stumbled upon following line in the [Agent part]( http://elixir-lang.org/getting-started/mix-otp/agent.html)
```
Now it is your turn to write a test for the functionality above!
```
I think such challenges are awesome for learning! It would be cool to peak how the pros solved it, so i can compare it to my solution.

Wouldn't it be beneficial to add a git repository with the current state of the application at the end of each section?

**Comment by EliotJones** [comment]
Hi, not that it's formatted correctly (nor am I a pro :smile: ) but I've uploaded my code from the full tutorial here:

https://github.com/EliotJones/elixir-mix-otp-tutorial

Hope this helps!

**Comment by davidspiess** [comment]
Thanks @EliotJones  :+1:

**Comment by eksperimental** [comment]
What I found missing when I read the guide was the actual source code for whatever was being explained, .. as there was a lot of "change this block for this" , and later "now replace this line with this one"... and I got lost many times, I think it will be good to link to source files at different stages in the exercise, just like in any regular book.

**Comment by josevalim** [comment]
The code is here: https://github.com/josevalim/kv_umbrella.

For now, we can at least add a link to the first chapter saying the final code is there and can be used as a reference

**Comment by davidspiess** [comment]
I think that would be enough :+1:
