### ISSUE TITLE
Elixir School Learning Page

### ISSUE THREAD

**Issue by pjhampton** [elixir-lang/elixir-lang.github.com#695]
Hey!

We have been working hard on Elixir-School which is community website with peer-reviewed lessons. The site is currently being translated to 6 other languages (Russian, Japanese, Spanish, Portuguese, Chinese, and Vietnamese) to make it more accessible to non-english speakers. We're using this website as a means of reinforcing our own learning and crowdsourcing knowledge.

http://elixirschool.com/
https://github.com/doomspork/elixir-school
https://twitter.com/elixirschool

Is there room at the moment for us on the learning page?

cc/ @doomspork

**Comment by josevalim** [comment]
:+1: let's do this!

**Comment by pjhampton** [comment]
@josevalim sweet! I will add a PR over the next day or so!

**Comment by pragmaticivan** [comment]
Nice!

**Comment by doomspork** [comment]
This is great, thank you @josevalim :grinning:
