### ISSUE TITLE
A link to the repository on every page (in the footer?)

### ISSUE THREAD

**Issue by lexmag** [elixir-lang/elixir-lang.github.com#696]
I think we should have something like this on every page:

> This website is [open source](https://github.com/elixir-lang/elixir-lang.github.com). See a typo? Please, [open an issue](https://github.com/elixir-lang/elixir-lang.github.com/issues).

Right now we mention this only once:  at [the beginning of getting started](http://elixir-lang.org/getting-started/introduction.html).

Inspired by [InfluxDB docs](https://docs.influxdata.com/influxdb/v0.10/query_language/functions/).

**Comment by josevalim** [comment]
Instead of "open an issue", I would link to the source code on Github so folks can press edit and submit the change. :)

**Comment by lexmag** [comment]
Closed in #697 and improved in #698.
