### ISSUE TITLE
openSUSE install repository needs to be updated on the "elixir-lang.org" website

### ISSUE THREAD

**Issue by sunnystormy** [elixir-lang/elixir-lang.github.com#712]
I noticed that the install repository provided for openSUSE users wasn't working on my machine (I run openSUSE Tumbleweed). The openSUSE erlang website suggests the "Factory" repo located at "http://download.opensuse.org/repositories/devel:/languages:/erlang/openSUSE_Factory/". I was able to install erlang and the latest version of elixir properly after getting the Factory repo set up.

Please update this on the installation page when you get a chance. Thank you!

**Comment by sunnystormy** [comment]
@josevalim Oh... I thought you could just change the URL on the "Installation" page on the website? What do you need me to do?

**Comment by josevalim** [comment]
Or, is it just a matter of changing the URL? So I can do that. Thank you! :)
