### ISSUE TITLE
Math.zero?(0.0) === false in getting-started/modules

### ISSUE THREAD

**Issue by allonhadaya** [elixir-lang/elixir-lang.github.com#722]
In the current implementation, the following is true

```elixir
Math.zero?(0.0) === false
```

It might be more correct to offer the following code instead. It makes it clear to the student that `0` does not match with `0.0`.

```elixir
defmodule Math do
  def zero?(0), do: true
  def zero?(0.0), do: true
  def zero?(x) when is_number(x), do: false
end
```

```elixir
Math.zero?(0.0) === true
```

**Comment by josevalim** [comment]
That's a great point. Maybe we should focus on it to only work with integers but something surely should be done.

**Comment by allonhadaya** [comment]
That's a great point... Maybe:

```elixir
defmodule Math do
  def zero?(0), do: true
  def zero?(x) when is_integer(x), do: false
end
```
An example could still be used to demonstrate what happens with `0.0`.

**Comment by josevalim** [comment]
@allonhadaya that would be perfect. Can you please send a pull request?

**Comment by allonhadaya** [comment]
@josevalim how does it look? #724

**Comment by josevalim** [comment]
Beautiful, thank you!
