### ISSUE TITLE
Misspelled on page GenServer

### ISSUE THREAD

**Issue by Gabriel-Araujo** [elixir-lang/elixir-lang.github.com#738]
Wrong spelling in GenServer page at the beginning of the topic "Our first GenServer".

at
_"Create a new file at lib/kv/registry.ex with the following contents:"_

The folder path is changed.
The correct would be: "**kv/lib**/registry.ex" and not "**lib/kv**/registry.ex"

**Comment by whatyouhide** [comment]
The `lib/kv/registry.ex` path is correct IMO. In Elixir, by convention, all library code (so not tests for example) goes into `project_root/lib`. Then, directories should mirror the naming of modules, with one directory for each part of the module name separated by `.`. For example, `Foo.Bar` goes in `lib/foo/bar.ex` and, in this case, `KV.Registry` goes in `lib/kv/registry`.

Does it make sense? 😃

**Comment by Gabriel-Araujo** [comment]
You're correct I was wrong...
Now I get it. I was wrong because the project name is also KV

so
project_root/lib/module/file.ex
it is
kv/lib/kv/registry.ex
