### ISSUE TITLE
About i18n support

### ISSUE THREAD

**Issue by riseshia** [elixir-lang/elixir-lang.github.com#752]
Hi, I have one question about i18n of this.
Is there any plan to support i18n?
Always thanks to your effort!

**Comment by whatyouhide** [comment]
@riseshia hey there, you mean plans to support translating Elixir's website to other languages?

**Comment by riseshia** [comment]
@whatyouhide yes, exactly.

**Comment by josevalim** [comment]
You should check ElixirSchool for initiatives that aim to bring Elixir to multiple languages: https://elixirschool.com/

**Comment by riseshia** [comment]
Oh, I don't know about that. Thanks a lot! I would contribute there :)
