### ISSUE TITLE
Incorrect code snippet used in crash-course for Partials?

### ISSUE THREAD

**Issue by jdicioccio** [elixir-lang/elixir-lang.github.com#779]
See below:

![image](https://cloud.githubusercontent.com/assets/171162/16314900/d91d8da8-3934-11e6-833b-ae945de0fada.png)

I believe the second example is incorrect (it's also the same example used directly above in the first-class functions example.

**Comment by josevalim** [comment]
I have just executed all examples in my terminal to double check and everything worked correctly. What am I missing?

**Comment by sgtpepper43** [comment]
I was literally about to post this issue. The second example doesn't show how partials work is the problem.

**Comment by sgtpepper43** [comment]
It should be something like
```elixir
defmodule Math do
  def multiply(x, y) do
    x * y
  end
end

Enum.map [1, 2, 3, 4], &(Math.multiply(&1, 2))
#=> [2, 4, 6, 8]
```

**Comment by ericmj** [comment]
@sgtpepper43 We still need to show the existing examples. If you can send PR that also adds your example with an explanation that would be very appreciated.

@jdicioccio Can you specify what is incorrect since all code seem to be working correctly?

**Comment by josevalim** [comment]
I have *just* fixed this in master. I changed the headings. :)
