### ISSUE TITLE
Is there a plan to support other languages for this website

### ISSUE THREAD

**Issue by markgeek** [elixir-lang/elixir-lang.github.com#790]
I am a Chinese developer, because of loving this fantastic language,  I'd like to translate this website into Chinese to let more Chinese people to know it. I'm not sure whether it's already under working or not.

![1](https://cloud.githubusercontent.com/assets/888252/16572159/01074180-4298-11e6-8d60-8ca62ae33c56.png)

**Comment by eksperimental** [comment]
hi mark.
you may find interesting this https://github.com/elixir-cn

/cc @jw2013

**Comment by jw2013** [comment]
@falood @lidashuang @developerworks @Kabie I might be wrong since it has been a while, but I remember someone might already translated this? do you guys know? (might be one of you guys haha) thanks!

**Comment by falood** [comment]
I have forked it [here](https://github.com/elixir-cn/elixir-lang.github.com) and added @markgeek to `elixir-cn` org.
@jw2013 do you means [this](https://github.com/elixir-lang-china/elixir_guide_cn)?  It seems that it's an old version, but we can upgrade it.

**Comment by josevalim** [comment]
Thank you @markgeek!

We don't plan to host different languages ourselves but you can translate the content as long as you keep the proper copyright notices. :) We also recommend https://elixirschool.com/ which was designed specifically to host multiple languages!

**Comment by jw2013** [comment]
@falood oh yeah, that is what I was looking for. 👍 

thanks!!

**Comment by markgeek** [comment]
@jw2013 @falood Thanks
