### ISSUE TITLE
Error running test from 'Our first GenServer' section

### ISSUE THREAD

**Issue by garrardkitchen** [elixir-lang/elixir-lang.github.com#798]
Hi,

I've been on the elixir earning curve now for 1 week. I'm at this page: http://elixir-lang.org/getting-started/mix-otp/genserver.html.

When I follow the instructions outlined in http://elixir-lang.org/getting-started/mix-otp/genserver.html#our-first-genserver and http://elixir-lang.org/getting-started/mix-otp/genserver.html#testing-a-genserver and run `mix test` I get this:

```
1) test spawns buckets (KV.RegistryTest)
     test/kv/registry_test.exs:9
     ** (EXIT from #PID<0.120.0>) an exception was raised:
         ** (UndefinedFunctionError) function KV.Bucket.start_link/0 is undefined (module KV.Bucket is not available)
             KV.Bucket.start_link()
             (otp_playground) lib/kv/registry.ex:43: KV.Registry.handle_cast/2
             (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
             (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3



Finished in 0.04 seconds
1 test, 1 failure

Randomized with seed 963082

16:53:28.030 [error] GenServer #PID<0.121.0> terminating
** (UndefinedFunctionError) function KV.Bucket.start_link/0 is undefined (module KV.Bucket is not available)
    KV.Bucket.start_link()
    (otp_playground) lib/kv/registry.ex:43: KV.Registry.handle_cast/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:create, "shopping"}}
State: %{}
```

What am I doing wrong?

Warmest regards,

Garrard.

**Comment by josevalim** [comment]
The error message says "module is not being defined" so I would investigate
if you have a file inside lib such as:

* it has extension .ex
* it defines a module called KV.Bucket

It is probably a typo or something similar.

On Friday, July 8, 2016, Garrard Kitchen <notifications@github.com> wrote:

> Hi,
>
> I've been on the elixir earning curve now for 1 week. I'm at this page:
> http://elixir-lang.org/getting-started/mix-otp/genserver.html.
>
> When I follow the instructions outlined in
> http://elixir-lang.org/getting-started/mix-otp/genserver.html#our-first-genserver
> and
> http://elixir-lang.org/getting-started/mix-otp/genserver.html#testing-a-genserver
> and run mix test I get this:
>
> 1) test spawns buckets (KV.RegistryTest)
>      test/kv/registry_test.exs:9
>      ** (EXIT from #PID<0.120.0>) an exception was raised:
>          ** (UndefinedFunctionError) function KV.Bucket.start_link/0 is undefined (module KV.Bucket is not available)
>              KV.Bucket.start_link()
>              (otp_playground) lib/kv/registry.ex:43: KV.Registry.handle_cast/2
>              (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
>              (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
>              (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
>
>
>
> Finished in 0.04 seconds
> 1 test, 1 failure
>
> Randomized with seed 963082
>
> 16:53:28.030 [error] GenServer #PID<0.121.0> terminating
> ** (UndefinedFunctionError) function KV.Bucket.start_link/0 is undefined (module KV.Bucket is not available)
>     KV.Bucket.start_link()
>     (otp_playground) lib/kv/registry.ex:43: KV.Registry.handle_cast/2
>     (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
>     (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
>     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
> Last message: {:"$gen_cast", {:create, "shopping"}}
> State: %{}
>
> What am I doing wrong?
>
> Warmest regards,
>
> Garrard.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir-lang.github.com/issues/798>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAAlbrD4oaWEdoPEblaMEouXoN3OphWDks5qTnS8gaJpZM4JIKwg>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by garrardkitchen** [comment]
The test code is this:
```
defmodule KV.RegistryTest do
  use ExUnit.Case, async: true

  setup do
    {:ok, registry} = KV.Registry.start_link
    {:ok, registry: registry}
  end

  test "spawns buckets", %{registry: registry} do
    assert KV.Registry.lookup(registry, "shopping") == :error

    KV.Registry.create(registry, "shopping")
    assert {:ok, bucket} = KV.Registry.lookup(registry, "shopping")
    #
    KV.Bucket.put(bucket, "milk", 1)
    assert KV.Bucket.get(bucket, "milk") == 1
  end
end
```

So based on what you've suggested I'm thinking either `KV.Bucket` inclusion here is wrong OR I'm missing some module or statement that should make `KV.Bucket` available.  The `KV.Registry` (lib/kv/registry.ex) module does make reference to `KV.Bucket` too.

I'm sure when I start to investigate [properly!] I'll understand what's wrong.

Warmest regards,

Garrard.

**Comment by garrardkitchen** [comment]
I needed bucket.ex (KV.Bucket) [https://github.com/elkinsd/elixir-kv/blob/master/lib/kv/bucket.ex] to get it to work.  Test now passes.
