### ISSUE TITLE
Clearly mark chapters as being part of the "Mix and OTP" guide

### ISSUE THREAD

**Issue by sotte** [elixir-lang/elixir-lang.github.com#834]
The chapters of the "Mix and OTP" guide are, no surprise here, part of the "Mix and OTP" guide and often depend on the previous chapters. When a google result brings you to one of the chapters this is not apparent though.

I would add a little note to the beginning of all chapters in the "Mix and OTP" guide, something like this

```
Note that this chapter is part of the "Mix and OTP" guide and depends on the previous chapters.
Maybe read the [TODO add link](previous chapter) or start reading from the [http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html](first chapter) of the guide.
```

If you're interested in this I would create a pull request.

**Comment by whatyouhide** [comment]
This is not a bad idea IMO, and I lean on being 👍 on this (or something similar to this). Let's hear what the others think :)

**Comment by josevalim** [comment]
Sounds good to me!

**Comment by sotte** [comment]
OK, I'll put a pull request together tomorrow.
