### ISSUE TITLE
Adding workwithelixir to the community section

### ISSUE THREAD

**Issue by imkmf** [elixir-lang/elixir-lang.github.com#835]
I launched WorkWithElixir (https://workwithelixir.com/) over the weekend–it's an Elixir/Phoenix job board. I noticed the community section of the site on the sidebar, would y'all consider adding a job board to that? Let me know – I can work up the PR.

**Comment by whatyouhide** [comment]
I'm not sure about this since there are already a few job boards in the Elixir community (like [this one](http://jobs.elixirdose.com) for example) and we don't have any of them in the sidebar 😕

**Comment by imkmf** [comment]
ah, ok! I wasn't sure if that discussion had been had before, thought I would ask – no worries! 😄 Want me to close this out?

**Comment by whatyouhide** [comment]
@josevalim wdyt we should do about this? :)

**Comment by josevalim** [comment]
Let's close for now. As you said, there are many job boards and they don't belong to the community section per-se. Maybe we could create a page to list of all them but I am not sure if it is helpful. Thank you @imkmf.
