### ISSUE TITLE
"Operators" documentation is nowhere to be found

### ISSUE THREAD

**Issue by davidkumru** [elixir-lang/elixir-lang.github.com#840]
The link to the "Operators" documentation at the bottom of this page leads to a "Page not found": [http://elixir-lang.org/getting-started/basic-operators.html](http://elixir-lang.org/getting-started/basic-operators.html).

Searching the docs for a dedicated "Operators" page also yields no results.

Maybe the following link is an appropriate replacement?: [http://elixir-lang.org/docs/stable/elixir/Kernel.html#functions](http://elixir-lang.org/docs/stable/elixir/Kernel.html#functions).

**Comment by whatyouhide** [comment]
@davidenglishmusic that documentation is not present in the "stable" docs yet, it should be in the "master" docs since it has been recently added. @josevalim I don't see this even in the master docs though, maybe we didn't build this docs for some reason? 😕

**Comment by josevalim** [comment]
Maybe whatever we are using to build the docs is not working lately? I will do it manually. /cc @ericmj

**Comment by josevalim** [comment]
Sorry @ericmj, false alarm.

@whatyouhide we forgot to update the Makefile. :bowtie: It should be fixed now!

**Comment by whatyouhide** [comment]
Ops, my bad then 😬 Thanks for adding both pages!
