### ISSUE TITLE
Proposal: Getting Started Guide in EPUB Format

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/elixir-lang.github.com#860]
As a way to find new features for [BUPE](https://github.com/milmazz/bupe), I've been working on [elixir_getting_started_guide_to_go](https://github.com/milmazz/elixir_getting_started_guide_to_go), which is a module that converts the _current_ content of the [Getting Started Guide](http://elixir-lang.org/getting-started/introduction.html) into an EPUB document. According to [epubcheck](https://github.com/IDPF/epubcheck) the EPUB document is valid :)

What do you think of providing other formats of the _Getting Started Guide_?, here are some screenshots:

![screen shot 2016-10-04 at 10 57 06 pm](https://cloud.githubusercontent.com/assets/34700/19100610/0709fbdc-8a86-11e6-9ca5-dd3697deaf93.png)

![screen shot 2016-10-04 at 10 57 26 pm](https://cloud.githubusercontent.com/assets/34700/19100616/11bd70f4-8a86-11e6-8e60-1a0a23da5755.png)

![screen shot 2016-10-04 at 11 02 45 pm](https://cloud.githubusercontent.com/assets/34700/19100690/b55c00b8-8a86-11e6-9315-9b269bd39d9f.png)

Of course, there are some things to do, like improving the styles (help wanted) and at least include [highlight.js](https://highlightjs.org/) for the scripts, but first, I'll add the option to include custom CSS & JS in [BUPE](https://github.com/milmazz/bupe).

**Comment by josevalim** [comment]
Beautiful! This has been asked multiple times and being able to do it in Elixir makes me much more comfortable with supporting it and making it part of our official documents!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by milmazz** [comment]
@josevalim Great to know that you like it :)

Should we also include the *Mix and OTP* and *Meta-programming in Elixir* sections in the EPUB document?

**Comment by josevalim** [comment]
@milmazz if we can make those distinct parts, then yes. Otherwise we can have three separate epubs too.

**Comment by milmazz** [comment]
Current status (initial support for highlight.js and custom css):

![screen shot 2016-10-11 at 12 20 03 am](https://cloud.githubusercontent.com/assets/34700/19259598/d592e0a6-8f48-11e6-9ce5-6b2e4a1ad97b.png)

**Comment by josevalim** [comment]
Beautiful. Should we use light colors? The same we use on ExDoc?

**Comment by milmazz** [comment]
@josevalim That was just a test that I did to demonstrate that we already support custom CSS (Solarized) and custom JS (`highlight.js`). I can try to emulate all the styles from ExDoc as you suggested. Maybe @dignifiedquire want to help us again :)

BTW, what do you think about the font? should we support custom fonts also?

**Comment by josevalim** [comment]
@milmazz great! To be honest, we don't need to support anything. We could even ship with the code font-style above. It doesn't need to be closer to the one on the website either.

To me, the most important features we are getting from this: 1. tooling to publish in EPUB 2. the guides in EPUB. Once we do those, if someone wants a custom font, then they can send a pull request to the tooling or to the website. :)

**Comment by milmazz** [comment]
@josevalim You can find the *getting started* and *meta-programming* guides in the following archive:

[elixir-getting-started-guide.zip](https://github.com/elixir-lang/elixir-lang.github.com/files/523385/elixir-getting-started-guide.zip)

**Comment by josevalim** [comment]
@milmazz it looks excellent! What do we need to do to automate its generation? :)

**Comment by milmazz** [comment]
@josevalim Right now I'm doing this inside IEx:

```
iex(1)> ElixirGettingStartedGuide.run()
'/Users/.../elixir_getting_started_guide_to_go/elixir-getting-started-guide.epub'
iex(2)> ElixirGettingStartedGuide.run(guide: :mix_otp)
'/Users/.../elixir_getting_started_guide_to_go/mix-and-otp.epub'
iex(3)> ElixirGettingStartedGuide.run(guide: :meta)
'/Users/.../elixir_getting_started_guide_to_go/meta-programming-in-elixir.epub'
iex(4)> ElixirGettingStartedGuide.run(guide: "wat")
** (RuntimeError) invalid guide, allowed: :mix_otp, :meta or :getting_started
    (elixir_getting_started_guide) lib/elixir_getting_started_guide.ex:32: ElixirGettingStartedGuide.generate_nav/2
    (elixir_getting_started_guide) lib/elixir_getting_started_guide.ex:21: ElixirGettingStartedGuide.run/1
```

Please don't use the `mix-and-otp.epub` yet, `epubcheck` is reporting the following errors for now:

```console
java -jar ~/Downloads/epubcheck-4.0.1/epubcheck.jar mix-and-otp.epub
Validating using EPUB version 3.0.1 rules.
ERROR(RSC-005): mix-and-otp.epub/OEBPS/content/supervisor-and-application.xhtml(371,62): Error while parsing file 'value of attribute "width" is invalid; must be an integer'.
FATAL(RSC-016): mix-and-otp.epub/OEBPS/content/supervisor-and-application.xhtml(371,64): Fatal Error while parsing file 'The element type "img" must be terminated by the matching end-tag "</img>".'.
ERROR(RSC-005): mix-and-otp.epub/OEBPS/content/supervisor-and-application.xhtml(-1,-1): Error while parsing file 'The element type "img" must be terminated by the matching end-tag "</img>".'.
ERROR(RSC-007): mix-and-otp.epub/OEBPS/content/supervisor-and-application.xhtml(371,62): Referenced resource could not be found in the EPUB.

Check finished with errors
```

BTW, I would like this as an `escript`, but it seems not possible because `BUPE` depends on assets in `priv` and I don't know if I can use `devinus/markdown` as a dependency either, any advice?

**Comment by josevalim** [comment]
Dependencies will work on escript but not stuff in priv. One work around for the priv stuff is to load the information into the module. For example, move it from priv/ to templates/ and then during compilation:

```elixir
defmodule Foo do
  @foo_bar File.read!("templates/foo_bar")
  @baz_bat File.read!("templates/baz_bat")
  ...
end
```

**Comment by josevalim** [comment]
Actually, C dependencies will not work. But you can also use earmark for the markdown stuff, which is in pure Elixir.

**Comment by milmazz** [comment]
We're almost ready to go, I already made the changes that you suggested and now it's possible to use escript to do the conversion. The only missing thing is to solve some issues with Earmark and improve the CLI module, which btw right now is really dumb :)

**Comment by josevalim** [comment]
Sweet! Maybe the Earmark issues can be solved by setting the same setting as ExDoc? https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/markdown/earmark.ex#L29-L33

**Comment by RobertDober** [comment]
@josevalim unfortunately not, Milton caught an ugly bug of ours. I'll work on it soon.
@milmazz this is a beautiful effort 👍

**Comment by milmazz** [comment]
@RobertDober Thank you for the kind words and your work on Earmark. In the meantime, I'll focus on improving the documentation and the CLI module.

**Comment by milmazz** [comment]
@josevalim Today I did some changes to [elixir_getting_started_guide_to_go](https://github.com/milmazz/elixir_getting_started_guide_to_go) and also with the PR #899 with are ready to go, I already verified the 3 EPUBs files with `epubchecker` and everything is working as expected. Hope this help!

**Comment by josevalim** [comment]
This looks fantastic, thank you @milmazz! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

Do you believe it is worth integrating it to the repository? So we avoid copying assets and everything else? Do you think it is doable?

**Comment by milmazz** [comment]
@josevalim You mean to put all the [elixir_getting_starting_guide_to_go](https://github.com/milmazz/elixir_getting_started_guide_to_go) source code at the same level of the current Jekyll structure for `elixir-lang.github.com`? If I understood correctly, yes, it's feasible :)

**Comment by josevalim** [comment]
@milmazz yes! Ideally I would prefer to generate the pdf automatically in the current project by doing something such as `mix pdf` and then just committing the latest pdf version. :) Would you please send a PR? :heart:

**Comment by milmazz** [comment]
@josevalim s/pdf/epub/g, right? ;)

If you also want the PDF format, I think that we can provide 2 mix tasks, the first one will transform the HTML version to EPUB, and the second one should transform the EPUB to PDF (via third-party). We can use Calibre CLI `ebook-convert` tool or we can use Pandoc, among others.

**Comment by josevalim** [comment]
Sorry, I meant epub instead of PDF, yes.

**Comment by RobertDober** [comment]
@milmazz just a thought, once you have HTML would it not make more sense to convert to PDF directly?

**Comment by fcevado** [comment]
I know I'm arriving too late in the discussion, but [GitBook](https://www.gitbook.com), it includes a interface for [multiple languages](https://toolchain.gitbook.com/languages.html) and renders to html, pdf and epub. Just an example, [Elm Guide](https://guide.elm-lang.org) uses it.

**Comment by milmazz** [comment]
@fcevado I have downloaded the *Elm Guide* in EPUB format and I noticed that they are using EPUBv2, which is not bad, but you can miss some interesting features such as HTML5, SVG, MathML, and CSS3 support (EPUBv2 was based on a specific subset of CSS 2). Also, in EPUBv3 you'll find a better navigation system, better scripting (which was explicitly discouraged in EPUB 2), rich media (such audio and video via HTML5 standard `audio` and `video` tags), embedded fonts support, among others.  

```xml
<?xml version='1.0' encoding='utf-8'?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="uuid_id" version="2.0">
  <metadata xmlns:calibre="http://calibre.kovidgoyal.net/2009/metadata" xmlns:opf="http://www.idpf.org/2007/opf" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>An Introduction to Elm</dc:title>
```
HTH

**Comment by josevalim** [comment]
Closing in favor of the PR. :)
