### ISSUE TITLE
set by step github repository

### ISSUE THREAD

**Issue by zwhitchcox** [elixir-lang/elixir-lang.github.com#869]
Is there a step by step repository for each of the mix examples?

It would be really easy for you guys to create one, and it's really hard for me to figure out why my code isn't working, having no experience in the language.

**Comment by eksperimental** [comment]
there is not, but there is the final code for it
https://github.com/josevalim/kv_umbrella

**Comment by zwhitchcox** [comment]
Ok, well, I'm getting this error

```
** (UndefinedFunctionError) function :get_tcp.listen/2 is undefined (module :get_tcp is not available)                                  
                :get_tcp.listen(4040, [:binary, {:packet, :line}, {:active, false}, {:reuseaddr, true}])                                
    (kv_server) lib/kv_server.ex:7: KVServer.accept/1
```

**Comment by josevalim** [comment]
It should be `:gen_tcp.listen` and not `:get_tcp.listen`.

**Comment by zwhitchcox** [comment]
Ok, thank yoiu.
