### ISSUE TITLE
Document installation for Raspberry Pi

### ISSUE THREAD

**Issue by martinp** [elixir-lang/elixir-lang.github.com#873]
I spent a lot of time googling installation instructions for the Raspberry Pi, many results were outdated and many recommended compiling Erlang from source (not ideal on a slow ARM processor).

Trying to install the Debian package from https://www.erlang-solutions.com/resources/download.html for Raspbian gave me the following error:

```
$ dpkg -i esl-erlang_19.1-1\~raspbian\~jessie_armhf.deb
dpkg: error processing archive esl-erlang_19.1-1~raspbian~jessie_armhf.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 esl-erlang_19.1-1~raspbian~jessie_armhf.deb
```

So that package seems to be incorrectly packaged for amd64.

In the end I found http://www.antonfagerberg.com/blog/elixir-on-raspberry-pi/ and learned that the Erlang Solutions repository contains packages for `armhf`.

Replacing `wheezy` with `jessie` (latest Raspbian is `jessie`) in the instructions from the blog post, I ended up doing the following:
```
echo "deb http://packages.erlang-solutions.com/debian jessie contrib" > /etc/apt/sources.list.d/erlang-solutions.list
wget http://packages.erlang-solutions.com/debian/erlang_solutions.asc
sudo apt-key add erlang_solutions.asc
apt update
apt install elixir
```

Given the popularity of Raspberry Pis, I think this should be better documented on http://elixir-lang.org/install.html.

**Comment by josevalim** [comment]
Could you please send a pull request? It can be added between the Windows and Docker sections. Thank you!
