### ISSUE TITLE
Old docs should redirect to new docs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir-lang.github.com#921]
I realized the [docs](http://elixir-lang.org/docs.html) now are hosted in https://hexdocs.pm,
problem is that anybody linking to the older docs will still see an outdated version of the docs as docs are updated.
for example http://elixir-lang.org/docs/stable/ contains 1.3.4, and not 1.4.0
So the solution I propose is to make every page under the docs/ folder redirect to the corresponding page in  hexdocs.pm
trouble is that it is not that easy in github pages, so the solution i have already worked out is to replace every documentation page with a file that call a **redirect** layout, and this layout will determine what is the URL it needs to redirect to.
So if we are interested, I need a ZIP file with all the files under /docs/, and I will submit a PR

**Comment by josevalim** [comment]
@eksperimental  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

All the files are here: https://github.com/elixir-lang/docs

You can probably send a PR directly there.

I think we can replace all of them except by the logo. :)

**Comment by eksperimental** [comment]
great @josevalim 
so how will that work?, because all the html files will have this content:
```
---
layout: redirect
---
```
but the layout will be in this project

**Comment by josevalim** [comment]
@eksperimental that won't work. The projects are "isolated" from each other, I believe. I would simply change all files in that project to have a content similar to this: https://github.com/elixir-lang/docs/blob/gh-pages/index.html

Except they would point to the proper hexdocs link. We should be able to do so programatically. Let me know if I can help with anything. :) We can likely include the link to generate them in the repo as well.

**Comment by eksperimental** [comment]
well, I can just copy the generated files by Jekyll, and move them over here, it should work.
I can include the layout used and the shell command that replaces the original files with the redirect page.

**Comment by josevalim** [comment]
@eksperimental I would prefer not to because in the future we can just nuke the whole docs repo. and if we do so in this repo, it will leave a bunch of trash in history? :)

**Comment by eksperimental** [comment]
sorry, I meant "I can move them over **T**here" (the docs repo)

**Comment by josevalim** [comment]
Sounds good!

**Comment by eksperimental** [comment]
Jose, I just realized there is a potential problem with this solution, is that if you ever update 1.3, 1.2, 1.1, and/or 1.0 to a newer patch version, the docs will have to be regenerated.
what changes are that this happens?
if that is a possibility, then my suggestion is to nuke the "docs" repo, and build the redirect pages regularly,
I already have a layout, and I have create a `/_data/elixir_version.yml` file that continas all the latest elixir versions, which we can also use for the `docs.markdown` page, so updating a single data file updates the whole links in our website.
I submit a PR, since it is all done, and you can have a look.

you have mentioned earlier that you are not so keen on this idea because you may get rid of the `/docs/` folder in the future, but I think this is a bad idea. Once we publish a link and such important link as the docs, we should keep them for ever as there are hundreads of websites linking to the old links, the best we can do IMO.
that's what the redirect layout does. it keeps track of the pages that we move out of the site, and for whatever internal links we can use the redirect plugin that we are currently using.

what do you think?

**Comment by josevalim** [comment]
@eksperimental it is very unlikely we will release new versions for those and, if we do, it should be straight-forward to do a search and replace in the current docs, so don't worry about it. :) Thank you!

**Comment by eksperimental** [comment]
great. the only thing is remember doing it. ;-P
so no worries
