### ISSUE TITLE
Should we consider adding documentation that mentions how can one find their currently installed Elixir version ?

### ISSUE THREAD

**Issue by boddhisattva** [elixir-lang/elixir-lang.github.com#924]
I recently wanted to lookup the Elixir version that I had installed on my system, but wasn't able to find the relevant command easily. After finding out how to check one's current Elixir version, I wrote up a post on the same [here](https://medium.com/@mohnishgj/how-to-find-out-the-elixir-version-that-one-is-currently-using-608621c2d592#.tg3yow1wd) but I was wondering if you'd like to add this to the documentation on http://elixir-lang.org/. 

In case you'd like to add this to the documentation, I would be happy to submit a PR for the same. I was thinking http://elixir-lang.org/install.html would be a good place to add the relevant documentation pertaining to one's currently installed Elixir version. I was thinking of adding a point number 7. that would mention details on how one could check their currently installed Elixir version. 

Could you please let me know your thoughts on whether including the above mentioned documentation as part of http://elixir-lang.org/ would be handy ? Thank you.

**Comment by josevalim** [comment]
Great idea.I believe we can quickly mention `elixir -v` on both install and introduction pages. Something like: "If you already have Elixir installed, you can check its version any time by running `elixir -v`".

**Comment by eksperimental** [comment]
I would go with "elixir --version"

**Comment by boddhisattva** [comment]
Thanks Jose. Based on your suggestion, I was just looking up the [introduction page](http://elixir-lang.org/getting-started/introduction.html) and I found that there is already a mention of how one can find their elixir version there. It looks like I'd need to only add this on the [install page](http://elixir-lang.org/install.html).

@eksperimental  I'm happy to mention something like "If you already have Elixir installed, you can check its version any time by running either `elixir -v` or `elixir --version`". This would take into account what you and @josevalim have suggested. Kindly confirm if this works for both of you and I'll send a PR accordingly. Thanks.

**Comment by eksperimental** [comment]
Some command line programs use -V, some others use -v, so i suggested to use --version to make it easy on the new user and save her from remember yet another command option.. Using both will defeat that purpose, but its not a big deal

**Comment by josevalim** [comment]
Yeah, we just need one. No need to give both. :)

**Comment by boddhisattva** [comment]
Thanks both for your replies. In that case, I will go ahead and use `elixir --version` as part of my PR and will update the [introduction page](http://elixir-lang.org/getting-started/introduction.html) to also reflect the same syntax.

**Comment by boddhisattva** [comment]
I've just sent a [PR](https://github.com/elixir-lang/elixir-lang.github.com/pull/927/files) based on our above discussion. In the process of working on this, I found another page on [introduction to mix](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html) that was using the `elixir -v` syntax and I've updated the same to use `elixir --version` to maintain consistency throughout.

**Comment by whatyouhide** [comment]
Closing in favor of #927.
