### ISSUE TITLE
Suggestion: Diagrams of the applications built in the Getting Started Guide

### ISSUE THREAD

**Issue by FlorEtcheverry** [elixir-lang/elixir-lang.github.com#934]
Hello,
I've been following this guide for a while now, since I have to start a project with Elixir for the first time. It would be useful to include some diagrams of the applications and the architecture (including OTP) so that it could be clearer. I've only found some diagrams in [LearnYouSomeErlang](http://learnyousomeerlang.com/content) but I couldn't fully understand and relate them to the "kv" application.

Thank you.
Florencia.

**Comment by whatyouhide** [comment]
Hey @FlorEtcheverry, this sounds like a good idea to me. Would you be willing to work on this? If so, do you have recommendations on how to generate diagrams in a portable and easy-to-contribute-to way?

**Comment by smorin** [comment]
@FlorEtcheverry ping

**Comment by FlorEtcheverry** [comment]
Hello, I worked on this for a school project and I haven't touched it since. I remember it was quite difficult to me to understand the architecture, that's why it would have been nice to have the aid of some diagrams or visual support.
For diagrams I mostly use draw.io (online) but I don't know if it's the best option.

**Comment by josevalim** [comment]
This has been opened for a while and unfortunately we did not have any progress on this front, so I will go ahead and close the issue. If someone would like to contribute those diagrams, please reach out. :) Thanks.
