### ISSUE TITLE
Can we consider improving the documentation around the usage of default arguments for named functions?

### ISSUE THREAD

**Issue by boddhisattva** [elixir-lang/elixir-lang.github.com#936]
With reference to the documentation around the usage of default arguments mentioned [here](http://elixir-lang.org/getting-started/modules.html#default-arguments) I found the below code to be kinda confusing from a beginner's perspective. Although, one would ideally expect only `"hello"` to be the default argument wrt the named function below, the presence of `IO.puts` got me thinking in terms of why are we having that when talking about default arguments.

```
defmodule DefaultTest do
  def dowork(x \\ IO.puts "hello") do
    x
  end
end
```

Also, I found a much more clear example [here](http://elixir-lang.org/crash-course.html#default-values) on how to use default values wrt functions. IMHO it would be less confusing to having something similar wrt the [documentation of default arguments mentioned as part of the getting started page](http://elixir-lang.org/getting-started/modules.html#default-arguments).

Below is what I'd like to propose -

```
defmodule DefaultTest do
  def dowork(x \\ "hello") do
    x
  end
end

iex> DefaultTest.dowork
"hello"
iex> DefaultTest.dowork 123
123
iex> DefaultTest.dowork
"hello"
```

instead of

```
defmodule DefaultTest do
  def dowork(x \\ IO.puts "hello") do
    x
  end
end
iex> DefaultTest.dowork
hello
:ok
iex> DefaultTest.dowork 123
123
iex> DefaultTest.dowork
hello
:ok
```

Please let me know your thoughts on the above and I can accordingly submit a PR to fix this if there's a common need from thereon.

Thank you.

**Comment by josevalim** [comment]
The goal of using puts was to clear up any misconception of when the default argument is evaluated but I believe you are right, it ends up causing more confusion than helping. A PR is welcome then! :heart:
