### ISSUE TITLE
keywords-and-maps use syntax for referring to first argument of a function

### ISSUE THREAD

**Issue by nhooyr** [elixir-lang/elixir-lang.github.com#941]
But this is not introduced before.

http://elixir-lang.org/getting-started/keywords-and-maps.html#nested-data-structures

Right after

```
The update_in/2 macro is similar but allows us to pass a function that controls how the value changes. For example, let’s remove “Clojure” from Mary’s list of languages:
```

**Comment by josevalim** [comment]
@nhooyr good catch. We should use `fn languages -> List.delete(languages, "Clojure") end`. Can you please send a PR?

**Comment by nhooyr** [comment]
will do soon
