### ISSUE TITLE
unclear sentence in getting-started/processes

### ISSUE THREAD

**Issue by nhooyr** [elixir-lang/elixir-lang.github.com#943]
At http://elixir-lang.org/getting-started/processes.html#send-and-receive

it says `In the previous example, when the receive block gets executed the sender process may be already dead.` How can that be? In the previous example, no new process was created. A message was sent to the process itself.

**Comment by nhooyr** [comment]
Also, the second last example uses the inspect function without explaining what it does or why.

**Comment by josevalim** [comment]
> it says In the previous example, when the receive block gets executed the sender process may be already dead. How can that be? In the previous example, no new process was created. A message was sent to the process itself.

Good catch. This applies to the following example which uses spawn.

> Also, the second last example uses the inspect function without explaining what it does or why.

Another good call. `inspect` is used to convert any data structure to a string, so it can be used for logging, printing, etc.

Could you please provide another PR fixing those issues? Thank you! Your feedback for improving the guides is very appreciated!

**Comment by nhooyr** [comment]
Yea np, I just wanted to make sure my issues were actually valid before creating PRs. I'll make the PRs soon :D
