### ISSUE TITLE
`with` documentation

### ISSUE THREAD

**Issue by rawkode** [elixir-lang/elixir-lang.github.com#966]
Currently `with` is mentioned http://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html and I really can't work out why. My thoughts are that it should be mentioned and explained http://elixir-lang.org/getting-started/case-cond-and-if.html

I'm happy to work on something, I'd just like to get clarification that I make sense, as perhaps there's a reason it is where it is :+1:

**Comment by whatyouhide** [comment]
I think the reason is that we don't want to introduce this concept too early on since it's not fundamental to know at the stage `case` and `cond` are. The guide on the website is an introductory guide after all. Not sure though 😕

**Comment by josevalim** [comment]
@whatyouhide is right. :) The guide is not meant to be a full reference, so it is mentioned only later on with other assorted features.

**Comment by rawkode** [comment]
No problem. Thanks!
