### ISSUE TITLE
elixir-lang.org using ssl certificates to *.github.com

### ISSUE THREAD

**Issue by fcevado** [elixir-lang/elixir-lang.github.com#973]
![home_elixir](https://cloud.githubusercontent.com/assets/9992984/25053593/896704a0-212e-11e7-8b5c-f6aa897a35a8.png)

**Comment by eksperimental** [comment]
Thank you for the report @fcevado.
something like this in the header would do

```html
<script>
if (window.location.protocol == "https:") {
  window.location.protocol = "http:"
}
</script>
```

**Comment by josevalim** [comment]
I believe we should support HTTPS but GitHub unfortunately does not for pages on custom domains. We have a couple options:

    1. Redirect https access to https://elixir-lang.github.io (we would need to remove the redirect from elixir-lang.github.io here though

    2. Use a third-party service such as fast.ly for SSL

**Comment by ericmj** [comment]
I would recommend using Cloudflare for SSL in this case because we don't need tons of features and it's okay if updates are not instant.

**Comment by whatyouhide** [comment]
@ericmj do you think asking Cloudflare for a OSS sponsorship would make sense? How would we move this forward otherwise?

**Comment by ericmj** [comment]
Cloudflare is free for the things we need so we just need to set up the account. I can do it if that's the way we want to go, I have done the same thing for old Hexdocs.

**Comment by whatyouhide** [comment]
@ericmj oh, sweet. Well I don't see any downsides, @josevalim?

**Comment by josevalim** [comment]
@ericmj yes, please. Can you add me and @whatyouhide as co-owners or something of sorts?

**Comment by ericmj** [comment]
This is now set up.
