### ISSUE TITLE
Website translation

### ISSUE THREAD

**Issue by thiagomajesk** [elixir-lang/elixir-lang.github.com#978]
Hi, I would like to know if there is any intention whatsoever to translate the website / docs.
As a fellow Brazilian, I think it would encourage newcomers (myself included). 
Even though english is not a problem for "most" programmers, there is nothing like the comfort of your mother tongue. I think it would be great for spreading Elixir too.

BTW, if there is a chance, how would one contribute to the translations?

PS: One minor thing that I'd suggest for the website is improve Jekyll's code highlight, it eases the reading of the code snippets ;).

**Comment by eksperimental** [comment]
Hi @thiagomajesk: it has been previously discussed,
have a look at this thread:
https://github.com/elixir-lang/elixir-lang.github.com/issues/790

**Comment by josevalim** [comment]
As mentioned in #790:

> We don't plan to host different languages ourselves but you can translate the content as long as you keep the proper copyright notices. :) We also recommend https://elixirschool.com/ which was designed specifically to host multiple languages!

Thank you @thiagomajesk !
