### ISSUE TITLE
keywords syntax notice

### ISSUE THREAD

**Issue by 2nth0nyj** [elixir-lang/elixir-lang.github.com#980]
while i was trying to type this snippet into my shell, I inserted a space between 'a' and the following colon, and this is a syntax error. please add a comment after second expression to notice other readers.
iex> list = [{:a, 1}, {:b, 2}]
[a: 1, b: 2]
iex> list == [a: 1, b: 2] #colon after a, and a must be followed by a colon without any other characters.
true

**Comment by whatyouhide** [comment]
Hey @2nth0nyj, thanks for the report. I don't believe we should say that a space after `a` would result in a syntax error because after all if you try it you do get a syntax error, that should be enough. There are many syntax errors we're not mentioning after all :) What do you think?

**Comment by josevalim** [comment]
I agree with @whatyouhide. The guide is not meant to be a complete syntax reference, so there will be missing spots. But we rather focus on breadth rather than depth, so it is fine. :) Thank you for the report!

**Comment by eksperimental** [comment]
I don't know if it is possible, but looks like a common mistake people could do.

Would it be possible to give a similar SyntaxError, as when we omit the space after the colon?

```iex
iex(3)> [a:1]              
** (SyntaxError) iex:3: keyword argument must be followed by space after: a: 
    
iex(3)> [a :1]
** (SyntaxError) iex:3: unexpected token: ":" (column 4, codepoint U+003A)
```

**Comment by josevalim** [comment]
@eksperimental the problem is, if you write this code: "a : b", which error should we show?

**Comment by eksperimental** [comment]
@josevalim I see. so there's no way to determine we are inside a list when we come up with something like that, and not outside of it?
