### ISSUE TITLE
Incomplete example in docs basic-types.html#lists-or-tuples

### ISSUE THREAD

**Issue by bid** [elixir-lang/elixir-lang.github.com#986]
Hi. I just decided to give elixir a try about an hour ago. So the perfect moment to comment on where the docs are unclear. ;)

In http://elixir-lang.org/getting-started/basic-types.html#lists-or-tuples the last example on the page doesn't make much sense.

> Most of the time, Elixir is going to guide you to do the right thing. For example, there is an elem/2 function to access a tuple item but there is no built-in equivalent for lists:
```
iex> tuple = {:ok, "hello"}
{:ok, "hello"}
iex> elem(tuple, 1)
"hello"
```
This example leaves out the point of the sentence before it. How about this example instead? : 
```
iex> tuple = {:ok, "hello"}
{:ok, "hello"}
iex> elem(tuple, 1)
"hello"
iex> list = [:ok, "hello"]
[:ok, "hello"]
iex> elem(list, 1)        
** (ArgumentError) argument error
    :erlang.element(2, [:ok, "hello"])
```

**Comment by josevalim** [comment]
Thank you @bid! I think there is a distinction between "there is not equivalent of elem/2 for lists"  and "elem/2 doesn't work with lists". We are trying to convey the first message. Your example conveys the second. I am not sure how to proceed though. What do you think?

**Comment by bid** [comment]
Oh, I didn't think about my example like that. You're right of course. The original is fine. So it's the sentence before that. How about:

> Most of the time, Elixir is trying to guide you to do the right thing. For example, there is an elem/2 function to access a tuple item but a build in equivalent for lists wouldn't make sense:

**Comment by josevalim** [comment]
Given the original one portrays those ideas, I would vote to keep it as is then. :)

**Comment by bid** [comment]
Yeah, it'as fine. Feel free to close this issue unless you want to wait and see if somebody else has something to comment on it. :+1: 
I guess if you read less fast than I did, the meaning is clear enough. :)

**Comment by josevalim** [comment]
Awesome, thank for reporting and don't hesitate to open up another issue if you find something else!
