### ISSUE TITLE
Link to Études for Elixir under Learning Resources get redirected

### ISSUE THREAD

**Issue by kw7oe** [elixir-lang/elixir-lang.github.com#998]
In **Learning Resources**, under [In-depth Resources](https://elixir-lang.org/learning.html#in-depth-resources), after visiting the url of **Études for Elixir** (http://chimera.labs.oreilly.com/books/1234000001642), it get redirected to https://hpbn.co

<img width="1280" alt="screen shot 2017-07-09 at 12 43 50 pm" src="https://user-images.githubusercontent.com/12683067/27991289-52068a26-64a4-11e7-899f-2e002fae7c65.png">

I am not sure if it is an issue to be fixed. Perhaps it can be solved by linking the url to http://chimera.labs.oreilly.com/books/1234000001642/index.html

**Comment by josevalim** [comment]
Thanks @kw7oe! It seems to be a bug on O'Reilly side. So I would let them and/or the author now and then consider changing it the URL if it isn't fixed after some time.
